import JSZip from 'npm:jszip@3.10.1'
import iconv from 'npm:iconv-lite@0.6.3'

const PAGE='https://fertilizer-search.maff.go.jp/FertilizerRegistrationSearch'
const FALLBACK='https://hiryotouroku.my.salesforce-sites.com/FertilizerRegistrationSearch/'
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type'}
const norm=(s:unknown)=>String(s??'').normalize('NFKC').replace(/^\uFEFF/,'').replace(/\s+/g,'').replace(/[（）()]/g,'').toUpperCase()
function htmlDecode(s:string){return s.replace(/&#x([0-9a-f]+);/gi,(_,h)=>String.fromCodePoint(parseInt(h,16))).replace(/&#(\d+);/g,(_,d)=>String.fromCodePoint(Number(d))).replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'")}
function* csvRows(text:string){let row:string[]=[],field='',quoted=false;for(let i=0;i<text.length;i++){const ch=text[i];if(quoted){if(ch==='"'&&text[i+1]==='"'){field+='"';i++}else if(ch==='"')quoted=false;else field+=ch}else if(ch==='"')quoted=true;else if(ch===','){row.push(field);field=''}else if(ch==='\n'){row.push(field.replace(/\r$/,''));if(row.some(v=>v.trim()!==''))yield row;row=[];field=''}else field+=ch}if(field.length||row.length){row.push(field.replace(/\r$/,''));if(row.some(v=>v.trim()!==''))yield row}}
function headerIndex(h:string[],aliases:string[]){const nh=h.map(norm);for(const a of aliases){const i=nh.findIndex(x=>x===norm(a));if(i>=0)return i}for(const a of aliases){const na=norm(a),i=nh.findIndex(x=>x.includes(na));if(i>=0)return i}return-1}
const val=(r:string[],i:number)=>i>=0?String(r[i]??'').trim():''
function numVal(v:string){const m=v.normalize('NFKC').replace(/,/g,'').match(/-?\d+(?:\.\d+)?/);return m?Number(m[0]):null}
function dateVal(v:string){const m=v.normalize('NFKC').match(/(\d{4})[\/.\-年]\s*(\d{1,2})[\/.\-月]\s*(\d{1,2})/);return m?`${m[1]}-${m[2].padStart(2,'0')}-${m[3].padStart(2,'0')}`:null}
function decodeCsv(bytes:Uint8Array){if(bytes[0]===0xef&&bytes[1]===0xbb&&bytes[2]===0xbf)return new TextDecoder().decode(bytes.subarray(3));try{return new TextDecoder('utf-8',{fatal:true}).decode(bytes)}catch{return iconv.decode(bytes,'shift_jis')}}
function merge(a:any,b:any){const components={...(a.components||{}),...(b.components||{})},active=!a.lapse_status||!b.lapse_status;return{...a,...b,components,lapse_status:active?null:b.lapse_status,tn:b.tn??a.tn,an:b.an??a.an,nn:b.nn??a.nn,tp:b.tp??a.tp,cp:b.cp??a.cp,sp:b.sp??a.sp,wp:b.wp??a.wp,tk:b.tk??a.tk,ck:b.ck??a.ck,wk:b.wk??a.wk,smg:b.smg??a.smg,cmg:b.cmg??a.cmg,wmg:b.wmg??a.wmg,sca:b.sca??a.sca,cca:b.cca??a.cca,wca:b.wca??a.wca,search_text:active?String(b.search_text||'').replace(/満期失効|廃止失効/g,''):b.search_text}}
async function rpc(name:string,body:unknown,auth:string){const url=Deno.env.get('SUPABASE_URL')!,key=Deno.env.get('SUPABASE_ANON_KEY')!,res=await fetch(`${url}/rest/v1/rpc/${name}`,{method:'POST',headers:{'Content-Type':'application/json',apikey:key,Authorization:auth},body:JSON.stringify(body)}),text=await res.text();if(!res.ok){let msg=text;try{msg=JSON.parse(text)?.message||text}catch{}throw new Error(msg)}return text?JSON.parse(text):null}
async function fetchZip(){let last='';for(const pageUrl of[PAGE,FALLBACK]){try{const page=await fetch(pageUrl,{headers:{'User-Agent':'YagiGardenManager/1.0'}});if(!page.ok){last=`${page.status}`;continue}const html=await page.text(),m=html.match(/fileDownload\(\s*['"]([^'"]+)['"]\s*\)/i);if(!m){last='配布URLなし';continue}const res=await fetch(htmlDecode(m[1]),{redirect:'follow',headers:{'User-Agent':'YagiGardenManager/1.0','Referer':pageUrl}});if(!res.ok){last=`ZIP ${res.status}`;continue}const bytes=new Uint8Array(await res.arrayBuffer());if(bytes[0]!==0x50||bytes[1]!==0x4b){last='ZIP形式ではありません';continue}return{pageUrl,bytes}}catch(e){last=e instanceof Error?e.message:String(e)}}throw new Error(`農水省の全件CSVを取得できませんでした: ${last}`)}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return new Response(JSON.stringify({error:'Method Not Allowed'}),{status:405,headers:{...cors,'Content-Type':'application/json'}});const auth=req.headers.get('authorization')||'';if(!auth.startsWith('Bearer '))return new Response(JSON.stringify({error:'ログインが必要です'}),{status:401,headers:{...cors,'Content-Type':'application/json'}});try{const sourceDate=new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Tokyo'}).format(new Date()),token=crypto.randomUUID();await rpc('sync_official_fertilizer_chunk',{p_rows:[],p_sync_token:token,p_source_date:sourceDate},auth);const dl=await fetchZip(),zip=await JSZip.loadAsync(dl.bytes),entry=Object.values(zip.files).find(e=>!e.dir&&e.name.toLowerCase().endsWith('.csv'));if(!entry)throw new Error('ZIP内にCSVファイルがありません');const text=decodeCsv(await entry.async('uint8array')),it=csvRows(text),first=it.next();if(first.done)throw new Error('公式CSVが空です');const h=first.value,ix={reg:headerIndex(h,['登録番号']),regDate:headerIndex(h,['登録年月日']),name:headerIndex(h,['肥料の名称']),company:headerIndex(h,['肥料業者']),address:headerIndex(h,['住所']),type:headerIndex(h,['肥料種類名称']),lapse:headerIndex(h,['失効区分'])},pairs:Array<{c:number;a:number}>=[];for(let i=1;i<=16;i++){const c=headerIndex(h,[`成分コード${i}`]),a=headerIndex(h,[`保証成分量${i}（%）`,`保証成分量${i}(%)`,`保証成分量${i}`]);if(c>=0&&a>=0)pairs.push({c,a})}if(ix.reg<0||ix.name<0||ix.company<0||ix.type<0||pairs.length!==16)throw new Error('公式CSVの列構成を認識できませんでした');let chunk=new Map<string,any>(),rawRows=0,sent=0;async function flush(){if(!chunk.size)return;const rows=[...chunk.values()];sent+=Number(await rpc('sync_official_fertilizer_chunk',{p_rows:rows,p_sync_token:token,p_source_date:sourceDate},auth))||0;chunk=new Map()}
for(let z=it.next();!z.done;z=it.next()){const r=z.value,name=val(r,ix.name);if(!name)continue;rawRows++;const reg=val(r,ix.reg),company=val(r,ix.company),type=val(r,ix.type),lapse=val(r,ix.lapse),key=[reg,name,company,type].map(x=>x.normalize('NFKC').trim()).join('|'),components:Record<string,number>={};for(const p of pairs){const c=val(r,p.c).normalize('NFKC').trim().toUpperCase(),a=numVal(val(r,p.a));if(c&&a!==null)components[c]=a}const g=(c:string)=>components[c]??null,rec={source_key:key,registration_no:reg,registration_category:'',fertilizer_name:name,company_name:company,fertilizer_type:type,registration_date:dateVal(val(r,ix.regDate)),expiration_date:null,valid_period:'',address:val(r,ix.address),lapse_status:lapse,tn:g('TN'),an:g('AN'),nn:g('NN'),tp:g('TP'),cp:g('CP'),sp:g('SP'),wp:g('WP'),tk:g('TK'),ck:g('CK'),wk:g('WK'),smg:g('SMG'),cmg:g('CMG'),wmg:g('WMG'),sca:g('SCA'),cca:g('CCA'),wca:g('WCA'),components,search_text:[reg,name,company,type,val(r,ix.address),lapse].join(' ').normalize('NFKC'),source_url:PAGE};chunk.set(key,chunk.has(key)?merge(chunk.get(key),rec):rec);if(chunk.size>=500)await flush()}await flush();const total=Number(await rpc('finalize_official_fertilizer_sync',{p_sync_token:token,p_source_date:sourceDate,p_row_count:rawRows},auth))||0;return new Response(JSON.stringify({ok:true,sourceDate,rows:total,rawRows,collapsed:Math.max(rawRows-total,0),sent,csvFiles:[entry.name],sourcePage:dl.pageUrl}),{headers:{...cors,'Content-Type':'application/json','Cache-Control':'no-store'}})}catch(e){console.error('fertilizer sync failed',e);return new Response(JSON.stringify({error:e instanceof Error?e.message:String(e)}),{status:500,headers:{...cors,'Content-Type':'application/json','Cache-Control':'no-store'}})}})
