import JSZip from 'npm:jszip@3.10.1'
import iconv from 'npm:iconv-lite@0.6.3'

const SOURCE_PAGES=['https://fertilizer-search.maff.go.jp/FertilizerRegistrationSearch','https://hiryotouroku.my.salesforce-sites.com/FertilizerRegistrationSearch/']
const OFFICIAL_URL=SOURCE_PAGES[0]
const COMPONENT_CODES=['TN','AN','IAN','NN','INN','XNN','TP','CP','ICP','SP','ISP','WP','IWP','TK','CK','ICK','WK','IWK','AL','SSI','WSI','SMG','CMG','ICMG','WMG','IWMG','SMN','CMN','ICMN','WMN','IWMN','CB','WB','IWB','SCA','CCA','WCA','SS']
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type'}
const htmlDecode=(s:string)=>s.replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>')
const stripTags=(s:string)=>htmlDecode(s.replace(/<[^>]*>/g,'')).replace(/\s+/g,' ').trim()
const escapeRe=(s:string)=>s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')
const norm=(s:unknown)=>String(s??'').normalize('NFKC').replace(/^\uFEFF/,'').replace(/\s+/g,'').replace(/[（）()]/g,'').toUpperCase()
function cookiesFrom(res:Response){const h=res.headers as Headers&{getSetCookie?:()=>string[]};const arr=typeof h.getSetCookie==='function'?h.getSetCookie():[];const raw=arr.length?arr:[res.headers.get('set-cookie')||''];return raw.filter(Boolean).map(x=>x.split(';')[0]).join('; ')}
function attr(attrs:string,name:string){const m=attrs.match(new RegExp(`${name}\\s*=\\s*(["'])([\\s\\S]*?)\\1`,'i'));return m?htmlDecode(m[2]):''}
function allAnchors(html:string){const out:{attrs:string;text:string;href:string;onclick:string}[]=[];const re=/<a\b([^>]*)>([\s\S]*?)<\/a>/gi;let m;while((m=re.exec(html)))out.push({attrs:m[1],text:stripTags(m[2]),href:attr(m[1],'href'),onclick:attr(m[1],'onclick')});return out}
const looksLikeAll=(text:string)=>text.replace(/[・●\s]/g,'')==='全件'
function resolveMaybe(base:string,value:string){try{return new URL(htmlDecode(value),base).toString()}catch{return ''}}
function zipUrlIn(text:string,base:string){const m=htmlDecode(text).match(/((?:https?:\/\/|\/|\.\.?\/)[^"'<>\s]+\.zip(?:\?[^"'<>\s]*)?)/i);return m?resolveMaybe(base,m[1]):''}
const responseBytes=async(res:Response)=>new Uint8Array(await res.arrayBuffer())
const isZip=(b:Uint8Array)=>b.length>4&&b[0]===0x50&&b[1]===0x4b
const isCsvResponse=(r:Response,b:Uint8Array)=>{const ct=(r.headers.get('content-type')||'').toLowerCase();return ct.includes('csv')||(!isZip(b)&&ct.includes('text/plain'))}
async function downloadFromVisualforce(pageUrl:string,html:string,cookie:string,a:{attrs:string;text:string;href:string;onclick:string}){const js=htmlDecode(`${a.href} ${a.onclick}`);const direct=zipUrlIn(js,pageUrl);if(direct)return fetch(direct,{headers:{Cookie:cookie,'User-Agent':'YagiGardenManager/1.0'}});const fm=js.match(/document\.getElementById\(['"]([^'"]+)['"]\)/),formId=fm?.[1]||'',obj=js.match(/jsfcljs\([^,]+,\s*\{([\s\S]*?)\}\s*,/);if(!formId||!obj)return null;const f=html.match(new RegExp(`<form\\b([^>]*\\bid=["']${escapeRe(formId)}["'][^>]*)>([\\s\\S]*?)<\\/form>`,'i'));if(!f)return null;const params=new URLSearchParams(),ire=/<input\b([^>]*)>/gi;let im;while((im=ire.exec(f[2]))){const x=im[1],name=attr(x,'name');if(name&&(attr(x,'type')||'text').toLowerCase()==='hidden')params.set(name,attr(x,'value'))}const pair=/'([^']+)'\s*:\s*'([^']*)'/g;let pm;while((pm=pair.exec(obj[1])))params.set(htmlDecode(pm[1]),htmlDecode(pm[2]));return fetch(resolveMaybe(pageUrl,attr(f[1],'action')||pageUrl),{method:'POST',redirect:'follow',headers:{'Content-Type':'application/x-www-form-urlencoded','Cookie':cookie,'User-Agent':'YagiGardenManager/1.0','Referer':pageUrl},body:params.toString()})}
async function obtainOfficialDownload(){let last='';for(const pageUrl of SOURCE_PAGES){try{const page=await fetch(pageUrl,{headers:{'User-Agent':'YagiGardenManager/1.0'}});if(!page.ok){last=`${pageUrl}: ${page.status}`;continue}const cookie=cookiesFrom(page),html=await page.text(),a=allAnchors(html).find(x=>looksLikeAll(x.text));if(!a){last=`${pageUrl}: 全件リンクが見つかりません`;continue}let res:Response|null=null;if(a.href&&!/^javascript:/i.test(a.href)&&a.href!=='#')res=await fetch(resolveMaybe(pageUrl,a.href),{headers:{Cookie:cookie,'User-Agent':'YagiGardenManager/1.0','Referer':pageUrl}});else res=await downloadFromVisualforce(pageUrl,html,cookie,a);if(!res){last=`${pageUrl}: ダウンロード操作を解析できません`;continue}let bytes=await responseBytes(res);if(!isZip(bytes)&&!isCsvResponse(res,bytes)){const nested=zipUrlIn(new TextDecoder().decode(bytes),res.url||pageUrl);if(nested){res=await fetch(nested,{headers:{Cookie:cookie,'User-Agent':'YagiGardenManager/1.0','Referer':pageUrl}});bytes=await responseBytes(res)}}if(isZip(bytes)||isCsvResponse(res,bytes))return{pageUrl,bytes,isZip:isZip(bytes)};last=`${pageUrl}: ZIP/CSVではありません`}catch(e){last=e instanceof Error?e.message:String(e)}}throw new Error(`農水省の全件CSVを取得できませんでした: ${last}`)}
function decodeCsv(bytes:Uint8Array){if(bytes[0]===0xef&&bytes[1]===0xbb&&bytes[2]===0xbf)return new TextDecoder('utf-8').decode(bytes.subarray(3));try{const t=new TextDecoder('utf-8',{fatal:true}).decode(bytes);if(t.includes('肥料')||t.includes('登録'))return t}catch{}return iconv.decode(bytes,'shift_jis')}
function parseCsv(text:string){const out:string[][]=[];let row:string[]=[],field='',quoted=false;for(let i=0;i<text.length;i++){const ch=text[i];if(quoted){if(ch==='"'&&text[i+1]==='"'){field+='"';i++}else if(ch==='"')quoted=false;else field+=ch}else if(ch==='"')quoted=true;else if(ch===','){row.push(field);field=''}else if(ch==='\n'){row.push(field.replace(/\r$/,''));out.push(row);row=[];field=''}else field+=ch}if(field.length||row.length){row.push(field.replace(/\r$/,''));out.push(row)}return out.filter(r=>r.some(v=>String(v).trim()!==''))}
function headerIndex(h:string[],aliases:string[]){const nh=h.map(norm);for(const a of aliases){const i=nh.findIndex(x=>x===norm(a));if(i>=0)return i}for(const a of aliases.filter(x=>/[^A-Za-z]/.test(x))){const i=nh.findIndex(x=>x.includes(norm(a)));if(i>=0)return i}return-1}
const val=(r:string[],i:number)=>i>=0?String(r[i]??'').trim():''
function numVal(v:string){const m=v.normalize('NFKC').replace(/,/g,'').match(/-?\d+(?:\.\d+)?/);return m?Number(m[0]):null}
function dateVal(v:string){const m=v.normalize('NFKC').match(/(20\d{2})[\/.\-年]\s*(\d{1,2})[\/.\-月]\s*(\d{1,2})/);return m?`${m[1]}-${m[2].padStart(2,'0')}-${m[3].padStart(2,'0')}`:null}
function categoryFromFile(name:string){const n=name.normalize('NFKC');if(n.includes('都道府県'))return'国内生産登録(都道府県)';if(n.includes('国内')||n.includes('国登録'))return'国内生産登録(国)';if(n.includes('輸入'))return'輸入登録';if(n.includes('外国'))return'外国生産登録';if(n.includes('指定混合'))return'指定混合(国)';return''}
const jstDate=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Tokyo'}).format(new Date())
function mapCsv(rows:string[][],fileName:string){if(!rows.length)return[];let hi=rows.slice(0,15).findIndex(r=>r.some(c=>norm(c).includes('肥料名称')||norm(c)==='肥料の名称')&&r.some(c=>norm(c).includes('登録番号')||norm(c).includes('会社名')||norm(c).includes('肥料種類')));if(hi<0)hi=0;const h=rows[hi],idx={reg:headerIndex(h,['登録番号','登録番号等']),cat:headerIndex(h,['登録区分']),name:headerIndex(h,['肥料名称','肥料の名称','銘柄名']),company:headerIndex(h,['会社名','氏名又は名称','登録を受けた者の氏名又は名称','生産業者名','輸入業者名']),type:headerIndex(h,['肥料種類','肥料の種類']),regDate:headerIndex(h,['登録年月日','登録日']),expiry:headerIndex(h,['有効期限']),period:headerIndex(h,['有効期間']),address:headerIndex(h,['住所','所在地'])};const ci=new Map<string,number>();for(const code of COMPONENT_CODES){const a=[code];if(code==='TN')a.push('窒素全量');if(code==='TP')a.push('りん酸全量','リン酸全量');if(code==='TK')a.push('加里全量');if(code==='SMG')a.push('可溶性苦土');if(code==='CMG')a.push('く溶性苦土');if(code==='WMG')a.push('水溶性苦土');if(code==='SCA')a.push('可溶性石灰');if(code==='CCA')a.push('く溶性石灰');if(code==='WCA')a.push('水溶性石灰');ci.set(code,headerIndex(h,a))}const fallback=categoryFromFile(fileName),out:any[]=[];for(const r of rows.slice(hi+1)){const name=val(r,idx.name);if(!name)continue;const reg=val(r,idx.reg),cat=val(r,idx.cat)||fallback,company=val(r,idx.company),type=val(r,idx.type),components:Record<string,number>={};for(const code of COMPONENT_CODES){const x=numVal(val(r,ci.get(code)??-1));if(x!==null)components[code]=x}const get=(c:string)=>components[c]??null;out.push({source_key:[cat,reg,name,company].map(x=>x.normalize('NFKC').trim()).join('|'),registration_no:reg,registration_category:cat,fertilizer_name:name,company_name:company,fertilizer_type:type,registration_date:dateVal(val(r,idx.regDate)),expiration_date:dateVal(val(r,idx.expiry)),valid_period:val(r,idx.period),address:val(r,idx.address),tn:get('TN'),an:get('AN'),nn:get('NN'),tp:get('TP'),cp:get('CP'),sp:get('SP'),wp:get('WP'),tk:get('TK'),ck:get('CK'),wk:get('WK'),smg:get('SMG'),cmg:get('CMG'),wmg:get('WMG'),sca:get('SCA'),cca:get('CCA'),wca:get('WCA'),components,search_text:[reg,cat,name,company,type,val(r,idx.address)].join(' ').normalize('NFKC'),source_url:OFFICIAL_URL})}return out}
async function rpc(name:string,body:unknown,auth:string){const url=Deno.env.get('SUPABASE_URL')!,key=Deno.env.get('SUPABASE_ANON_KEY')!,res=await fetch(`${url}/rest/v1/rpc/${name}`,{method:'POST',headers:{'Content-Type':'application/json','apikey':key,'Authorization':auth},body:JSON.stringify(body)}),text=await res.text();if(!res.ok){let msg=text;try{msg=JSON.parse(text)?.message||text}catch{}throw new Error(msg)}return text?JSON.parse(text):null}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return new Response(JSON.stringify({error:'Method Not Allowed'}),{status:405,headers:{...cors,'Content-Type':'application/json'}});const auth=req.headers.get('authorization')||'';if(!auth.startsWith('Bearer '))return new Response(JSON.stringify({error:'ログインが必要です'}),{status:401,headers:{...cors,'Content-Type':'application/json'}});try{const sourceDate=jstDate(),syncToken=crypto.randomUUID();await rpc('sync_official_fertilizer_chunk',{p_rows:[],p_sync_token:syncToken,p_source_date:sourceDate},auth);const dl=await obtainOfficialDownload(),files:{name:string;bytes:Uint8Array}[]=[];if(dl.isZip){const zip=await JSZip.loadAsync(dl.bytes);for(const e of Object.values(zip.files))if(!e.dir&&e.name.toLowerCase().endsWith('.csv'))files.push({name:e.name,bytes:await e.async('uint8array')})}else files.push({name:'all.csv',bytes:dl.bytes});if(!files.length)throw new Error('ZIP内にCSVファイルがありません');const merged:any[]=[];for(const f of files)merged.push(...mapCsv(parseCsv(decodeCsv(f.bytes)),f.name));const unique=new Map<string,any>();for(const r of merged)if(r.source_key)unique.set(r.source_key,r);const records=[...unique.values()];if(!records.length)throw new Error('公式CSVから肥料データを抽出できませんでした');let sent=0;for(let i=0;i<records.length;i+=750){const chunk=records.slice(i,i+750);sent+=Number(await rpc('sync_official_fertilizer_chunk',{p_rows:chunk,p_sync_token:syncToken,p_source_date:sourceDate},auth))||0}const total=Number(await rpc('finalize_official_fertilizer_sync',{p_sync_token:syncToken,p_source_date:sourceDate,p_row_count:records.length},auth))||records.length;return new Response(JSON.stringify({ok:true,sourceDate,rows:total,parsed:records.length,sent,csvFiles:files.map(f=>f.name),sourcePage:dl.pageUrl}),{headers:{...cors,'Content-Type':'application/json','Cache-Control':'no-store'}})}catch(e){console.error('fertilizer sync failed',e);return new Response(JSON.stringify({error:e instanceof Error?e.message:String(e)}),{status:500,headers:{...cors,'Content-Type':'application/json','Cache-Control':'no-store'}})}})
