import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { Car, ChevronDown, ChevronUp, CircleAlert, Edit3, Fuel, Gauge, History, MapPin, Plus, RefreshCw, Search, Settings2, Tractor, Wrench, X } from 'lucide-react'
import { deleteEquipmentServiceRecord, loadEquipmentAssets, loadEquipmentServiceRecords, saveEquipmentAsset, saveEquipmentServiceRecord, type AcquisitionType, type EquipmentAsset, type EquipmentCategory, type EquipmentServiceRecord, type EquipmentStatus, type FuelType, type ServiceType } from '../lib/equipment'
import { useAppPermissions } from '../lib/permissions'

const nf=new Intl.NumberFormat('ja-JP')
const money=(v:number|null)=>v===null?'—':`¥${nf.format(Math.round(v))}`
const ymd=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Tokyo'}).format(new Date())
const categoryLabel:Record<EquipmentCategory,string>={AGRICULTURAL_MACHINE:'農機具・機械',TOOL:'農具・工具',VEHICLE:'車両',OTHER:'その他'}
const statusLabel:Record<EquipmentStatus,string>={NORMAL:'正常',CAUTION:'注意',REPAIR_NEEDED:'修理必要',UNDER_REPAIR:'修理中',OUT_OF_SERVICE:'使用停止',DISPOSED:'廃棄・退役'}
const fuelLabel:Record<FuelType,string>={NONE:'燃料なし',GASOLINE:'ガソリン',MIXED_OIL:'混合オイル',DIESEL:'軽油',ELECTRIC:'電気',BATTERY:'バッテリー',OTHER:'その他'}
const acquisitionLabel:Record<AcquisitionType,string>={PURCHASED:'購入',RECEIVED:'譲受',INHERITED:'引継・相続',LEASED:'リース',OTHER:'その他'}
const serviceLabel:Record<ServiceType,string>={REPAIR:'修理',MAINTENANCE:'整備',INSPECTION:'点検',OIL_CHANGE:'オイル交換',PART_REPLACEMENT:'部品交換',VEHICLE_INSPECTION:'車検',VEHICLE_TAX:'自動車税',INSURANCE:'保険',OTHER:'その他'}
const assetBlank={id:'',category:'AGRICULTURAL_MACHINE' as EquipmentCategory,name:'',manufacturer:'',modelNo:'',serialNo:'',acquisitionType:'PURCHASED' as AcquisitionType,acquisitionDate:'',purchasePrice:'',fuelType:'NONE' as FuelType,fuelNote:'',storageLocation:'',status:'NORMAL' as EquipmentStatus,conditionNote:'',vehicleRegistrationNo:'',vehicleInspectionExpiry:'',vehicleTaxDueDate:'',insuranceExpiry:'',nextMaintenanceDate:'',currentOdometerKm:'',currentHourMeter:'',note:'',active:true}
const recordBlank={id:'',equipmentId:'',recordType:'MAINTENANCE' as ServiceType,recordDate:ymd(),vendor:'',description:'',cost:'0',odometerKm:'',hourMeter:'',nextDueDate:'',statusAfter:'' as EquipmentStatus|'',conditionAfter:'',note:''}

function daysUntil(date:string){if(!date)return null;const d=new Date(`${date}T00:00:00`),t=new Date();t.setHours(0,0,0,0);return Math.round((d.getTime()-t.getTime())/86400000)}
function dueClass(date:string){const d=daysUntil(date);return d===null?'':d<0?'overdue':d<=30?'soon':''}
function dueText(date:string){const d=daysUntil(date);if(d===null)return '';if(d<0)return `${Math.abs(d)}日超過`;if(d===0)return '今日';return `あと${d}日`}

export default function EquipmentPage(){
  const { allowed }=useAppPermissions()
  const canManage=allowed('equipment.manage')
  const[assets,setAssets]=useState<EquipmentAsset[]>([]),[records,setRecords]=useState<EquipmentServiceRecord[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[success,setSuccess]=useState('')
  const[tab,setTab]=useState<'assets'|'history'>('assets'),[query,setQuery]=useState(''),[category,setCategory]=useState('ALL'),[status,setStatus]=useState('ALL'),[historyType,setHistoryType]=useState('ALL'),[expanded,setExpanded]=useState<string[]>([])
  const[assetOpen,setAssetOpen]=useState(false),[recordOpen,setRecordOpen]=useState(false),[busy,setBusy]=useState(false),[assetForm,setAssetForm]=useState(assetBlank),[recordForm,setRecordForm]=useState(recordBlank)

  async function refresh(){setLoading(true);setError('');try{const[a,r]=await Promise.all([loadEquipmentAssets(),loadEquipmentServiceRecords()]);setAssets(a);setRecords(r)}catch(e:any){setError(e?.message||'機械設備データを読み込めませんでした。')}finally{setLoading(false)}}
  useEffect(()=>{void refresh()},[])
  useEffect(()=>{if(!canManage){setAssetOpen(false);setRecordOpen(false)}},[canManage])

  const filteredAssets=useMemo(()=>{const q=query.trim().normalize('NFKC').toLowerCase();return assets.filter(a=>(category==='ALL'||a.category===category)&&(status==='ALL'||a.status===status)&&(!q||`${a.assetNo} ${a.name} ${a.manufacturer} ${a.modelNo} ${a.serialNo} ${a.storageLocation} ${a.conditionNote} ${a.vehicleRegistrationNo}`.normalize('NFKC').toLowerCase().includes(q)))},[assets,query,category,status])
  const filteredRecords=useMemo(()=>{const q=query.trim().normalize('NFKC').toLowerCase();return records.filter(r=>(historyType==='ALL'||r.recordType===historyType)&&(!q||`${r.assetNo} ${r.equipmentName} ${r.description} ${r.vendor} ${r.note}`.normalize('NFKC').toLowerCase().includes(q)))},[records,query,historyType])
  const activeAssets=assets.filter(a=>a.active&&a.status!=='DISPOSED')
  const alertAssets=activeAssets.filter(a=>['CAUTION','REPAIR_NEEDED','UNDER_REPAIR','OUT_OF_SERVICE'].includes(a.status))
  const dueAssets=activeAssets.filter(a=>{const d=daysUntil(a.nextDueDate);return d!==null&&d<=30})
  const totalPurchase=assets.reduce((s,a)=>s+(a.purchasePriceYen||0),0)

  function editAsset(a:EquipmentAsset){if(!canManage)return;setAssetForm({id:a.id,category:a.category,name:a.name,manufacturer:a.manufacturer,modelNo:a.modelNo,serialNo:a.serialNo,acquisitionType:a.acquisitionType,acquisitionDate:a.acquisitionDate,purchasePrice:a.purchasePriceYen===null?'':String(a.purchasePriceYen),fuelType:a.fuelType,fuelNote:a.fuelNote,storageLocation:a.storageLocation,status:a.status,conditionNote:a.conditionNote,vehicleRegistrationNo:a.vehicleRegistrationNo,vehicleInspectionExpiry:a.vehicleInspectionExpiry,vehicleTaxDueDate:a.vehicleTaxDueDate,insuranceExpiry:a.insuranceExpiry,nextMaintenanceDate:a.nextMaintenanceDate,currentOdometerKm:a.currentOdometerKm===null?'':String(a.currentOdometerKm),currentHourMeter:a.currentHourMeter===null?'':String(a.currentHourMeter),note:a.note,active:a.active});setAssetOpen(true);setError('');setSuccess('')}
  function addRecord(asset?:EquipmentAsset){if(!canManage)return;setRecordForm({...recordBlank,recordDate:ymd(),equipmentId:asset?.id||''});setRecordOpen(true);setError('');setSuccess('')}
  function editRecord(r:EquipmentServiceRecord){if(!canManage)return;setRecordForm({id:r.id,equipmentId:r.equipmentId,recordType:r.recordType,recordDate:r.recordDate,vendor:r.vendor,description:r.description,cost:String(r.costYen),odometerKm:r.odometerKm===null?'':String(r.odometerKm),hourMeter:r.hourMeter===null?'':String(r.hourMeter),nextDueDate:r.nextDueDate,statusAfter:r.statusAfter,conditionAfter:r.conditionAfter,note:r.note});setRecordOpen(true);setError('');setSuccess('')}

  async function submitAsset(e:FormEvent){e.preventDefault();if(!canManage)return setError('設備情報を変更する権限がありません。');setBusy(true);setError('');setSuccess('');try{const price=assetForm.purchasePrice===''?null:Number(assetForm.purchasePrice),odo=assetForm.currentOdometerKm===''?null:Number(assetForm.currentOdometerKm),hours=assetForm.currentHourMeter===''?null:Number(assetForm.currentHourMeter);if(price!==null&&(!Number.isFinite(price)||price<0))throw new Error('金額を確認してください。');await saveEquipmentAsset({id:assetForm.id||undefined,category:assetForm.category,name:assetForm.name,manufacturer:assetForm.manufacturer,modelNo:assetForm.modelNo,serialNo:assetForm.serialNo,acquisitionType:assetForm.acquisitionType,acquisitionDate:assetForm.acquisitionDate,purchasePriceYen:price,fuelType:assetForm.fuelType,fuelNote:assetForm.fuelNote,storageLocation:assetForm.storageLocation,status:assetForm.status,conditionNote:assetForm.conditionNote,vehicleRegistrationNo:assetForm.vehicleRegistrationNo,vehicleInspectionExpiry:assetForm.vehicleInspectionExpiry,vehicleTaxDueDate:assetForm.vehicleTaxDueDate,insuranceExpiry:assetForm.insuranceExpiry,nextMaintenanceDate:assetForm.nextMaintenanceDate,currentOdometerKm:odo,currentHourMeter:hours,note:assetForm.note,active:assetForm.active});setAssetOpen(false);setAssetForm(assetBlank);setSuccess(assetForm.id?'設備情報を更新しました。':'設備を登録しました。');await refresh()}catch(e:any){setError(e?.message||'設備の保存に失敗しました。')}finally{setBusy(false)}}
  async function submitRecord(e:FormEvent){e.preventDefault();if(!canManage)return setError('修理・整備履歴を変更する権限がありません。');setBusy(true);setError('');setSuccess('');try{if(!recordForm.equipmentId)throw new Error('対象設備を選択してください。');const cost=Number(recordForm.cost||0);if(!Number.isFinite(cost)||cost<0)throw new Error('金額を確認してください。');await saveEquipmentServiceRecord({id:recordForm.id||undefined,equipmentId:recordForm.equipmentId,recordType:recordForm.recordType,recordDate:recordForm.recordDate,description:recordForm.description,vendor:recordForm.vendor,costYen:cost,odometerKm:recordForm.odometerKm===''?null:Number(recordForm.odometerKm),hourMeter:recordForm.hourMeter===''?null:Number(recordForm.hourMeter),nextDueDate:recordForm.nextDueDate,statusAfter:recordForm.statusAfter,conditionAfter:recordForm.conditionAfter,note:recordForm.note});setRecordOpen(false);setRecordForm(recordBlank);setSuccess(recordForm.id?'履歴を更新しました。':'修理・整備履歴を登録しました。');await refresh()}catch(e:any){setError(e?.message||'履歴の保存に失敗しました。')}finally{setBusy(false)}}
  async function removeRecord(r:EquipmentServiceRecord){if(!canManage)return setError('修理・整備履歴を削除する権限がありません。');if(!window.confirm(`${r.equipmentName}「${r.description}」の履歴を削除しますか？`))return;setBusy(true);setError('');try{await deleteEquipmentServiceRecord(r.id);setSuccess('履歴を削除しました。');await refresh()}catch(e:any){setError(e?.message||'削除に失敗しました。')}finally{setBusy(false)}}

  return <div className="page equipment-page">
    <div className="page-head"><div><p className="eyebrow">EQUIPMENT</p><h1>機械設備管理</h1><p className="sub">農機具・農具・車両の取得情報、燃料、保管場所、状態、修理・整備、車検・税金を一元管理します。</p></div><div className="head-actions">{canManage&&<button className="primary-button" onClick={()=>{setAssetForm(assetBlank);setAssetOpen(true)}}><Plus size={17}/>設備を登録</button>}<button className="icon-button" onClick={()=>void refresh()} disabled={loading}><RefreshCw size={18} className={loading?'spin':''}/></button></div></div>
    {error&&<div className="notice error dashboard-notice">{error}</div>}{success&&<div className="notice success dashboard-notice">{success}</div>}

    <div className="metrics equipment-metrics"><div className="metric"><span>稼働設備</span><strong>{activeAssets.length}</strong><small>農機具・農具・車両</small></div><div className="metric"><span>要注意・修理</span><strong>{alertAssets.length}</strong><small>状態確認が必要</small></div><div className="metric"><span>期限警告</span><strong>{dueAssets.length}</strong><small>期限超過・30日以内</small></div><div className="metric"><span>取得金額</span><strong>{money(totalPurchase)}</strong><small>金額登録済み設備の合計</small></div></div>

    <div className="equipment-tabs"><button className={tab==='assets'?'active':''} onClick={()=>setTab('assets')}><Tractor size={17}/>設備台帳 <span>{assets.length}</span></button><button className={tab==='history'?'active':''} onClick={()=>setTab('history')}><History size={17}/>修理・整備履歴 <span>{records.length}</span></button></div>

    <section className="panel equipment-main-panel">
      <div className="equipment-toolbar"><div className="search-box"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={tab==='assets'?'設備名・型番・保管場所・車両番号で検索':'設備名・修理内容・業者で検索'}/></div>{tab==='assets'?<><select value={category} onChange={e=>setCategory(e.target.value)}><option value="ALL">すべての区分</option>{Object.entries(categoryLabel).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="ALL">すべての状態</option>{Object.entries(statusLabel).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></>:<><select value={historyType} onChange={e=>setHistoryType(e.target.value)}><option value="ALL">すべての履歴</option>{Object.entries(serviceLabel).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select>{canManage&&<button className="secondary-button" onClick={()=>addRecord()}><Plus size={16}/>履歴を登録</button>}</>}</div>

      {tab==='assets'?<div className="equipment-card-grid">{filteredAssets.map(a=>{const open=expanded.includes(a.id);return <article className={`equipment-card status-${a.status.toLowerCase()}`} key={a.id}>
        <div className="equipment-card-head"><div className="equipment-title"><span className="equipment-category">{a.category==='VEHICLE'?<Car size={16}/>:<Tractor size={16}/>} {categoryLabel[a.category]}</span><h3>{a.name}</h3><p>{[a.manufacturer,a.modelNo&&`型番 ${a.modelNo}`].filter(Boolean).join(' / ')||'メーカー・型番未設定'}</p></div><span className={`equipment-status ${a.status.toLowerCase()}`}>{statusLabel[a.status]}</span></div>
        {a.conditionNote&&<div className="equipment-condition"><CircleAlert size={15}/><span>{a.conditionNote}</span></div>}
        <div className="equipment-quick-grid"><div><Fuel size={14}/><span>燃料</span><b>{fuelLabel[a.fuelType]}{a.fuelNote?` / ${a.fuelNote}`:''}</b></div><div><MapPin size={14}/><span>保管</span><b>{a.storageLocation||'未設定'}</b></div><div><Gauge size={14}/><span>使用量</span><b>{a.category==='VEHICLE'?(a.currentOdometerKm!==null?`${nf.format(a.currentOdometerKm)} km`:'未設定'):(a.currentHourMeter!==null?`${nf.format(a.currentHourMeter)} h`:'未設定')}</b></div></div>
        {a.nextDueDate&&<div className={`equipment-due ${dueClass(a.nextDueDate)}`}><Settings2 size={15}/><span>次回期限</span><b>{a.nextDueDate}</b><em>{dueText(a.nextDueDate)}</em></div>}
        <button className="equipment-expand" onClick={()=>setExpanded(v=>v.includes(a.id)?v.filter(x=>x!==a.id):[...v,a.id])}>{open?'詳細を閉じる':'詳細を見る'}{open?<ChevronUp size={16}/>:<ChevronDown size={16}/>}</button>
        {open&&<div className="equipment-detail"><div className="equipment-detail-grid"><div><span>管理番号</span><b>{a.assetNo}</b></div><div><span>取得</span><b>{acquisitionLabel[a.acquisitionType]} {a.acquisitionDate||'日付不明'}</b></div><div><span>取得金額</span><b>{money(a.purchasePriceYen)}</b></div><div><span>製造番号</span><b>{a.serialNo||'—'}</b></div><div><span>修理回数</span><b>{a.repairCount}回</b></div><div><span>修理・整備累計</span><b>{money(a.lifetimeServiceCostYen)}</b></div></div>
          {a.category==='VEHICLE'&&<div className="vehicle-obligations"><div><span>車両番号</span><b>{a.vehicleRegistrationNo||'—'}</b></div><div className={dueClass(a.vehicleInspectionExpiry)}><span>車検期限</span><b>{a.vehicleInspectionExpiry||'—'}</b></div><div className={dueClass(a.vehicleTaxDueDate)}><span>税金期限</span><b>{a.vehicleTaxDueDate||'—'}</b></div><div className={dueClass(a.insuranceExpiry)}><span>保険期限</span><b>{a.insuranceExpiry||'—'}</b></div></div>}
          {a.nextMaintenanceDate&&<p className="equipment-note">次回整備：{a.nextMaintenanceDate}</p>}{a.note&&<p className="equipment-note">{a.note}</p>}
          {canManage&&<div className="equipment-card-actions"><button onClick={()=>editAsset(a)}><Edit3 size={14}/>設備情報を編集</button><button onClick={()=>addRecord(a)}><Wrench size={14}/>修理・整備を登録</button></div>}
        </div>}
      </article>})}{!loading&&!filteredAssets.length&&<p className="empty">該当する設備はありません。</p>}</div>:<div className="equipment-history-list">{filteredRecords.map(r=><article className="equipment-history-card" key={r.id}><div className="equipment-history-date"><span>{r.recordDate}</span><b>{serviceLabel[r.recordType]}</b></div><div className="equipment-history-main"><h3>{r.equipmentName}</h3><p>{r.description}</p><div className="equipment-history-meta">{r.vendor&&<span>依頼先：{r.vendor}</span>}<span>費用：{money(r.costYen)}</span>{r.odometerKm!==null&&<span>{nf.format(r.odometerKm)} km</span>}{r.hourMeter!==null&&<span>{nf.format(r.hourMeter)} h</span>}{r.nextDueDate&&<span className={dueClass(r.nextDueDate)}>次回：{r.nextDueDate}</span>}</div>{r.conditionAfter&&<small>作業後：{r.conditionAfter}</small>}{r.note&&<small>{r.note}</small>}</div>{canManage&&<div className="equipment-history-actions"><button onClick={()=>editRecord(r)}><Edit3 size={15}/></button><button className="danger-text" disabled={busy} onClick={()=>void removeRecord(r)}><X size={15}/></button></div>}</article>)}{!loading&&!filteredRecords.length&&<p className="empty">修理・整備履歴はまだありません。</p>}</div>}
    </section>

    {canManage&&assetOpen&&<div className="inventory-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)setAssetOpen(false)}}><section className="panel inventory-modal equipment-modal"><div className="section-head"><div><p className="eyebrow">EQUIPMENT ASSET</p><h2>{assetForm.id?'設備情報を編集':'設備を登録'}</h2></div><button className="close-detail" onClick={()=>setAssetOpen(false)} disabled={busy}><X size={17}/></button></div><form className="equipment-form" onSubmit={submitAsset}>
      <div className="form-grid two"><label>設備区分<select value={assetForm.category} onChange={e=>setAssetForm({...assetForm,category:e.target.value as EquipmentCategory})}>{Object.entries(categoryLabel).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>名前<input required value={assetForm.name} onChange={e=>setAssetForm({...assetForm,name:e.target.value})} placeholder="例：アリミツ 動噴 / 1tトラック"/></label></div>
      <div className="form-grid two"><label>メーカー<input value={assetForm.manufacturer} onChange={e=>setAssetForm({...assetForm,manufacturer:e.target.value})}/></label><label>品番・型番<input value={assetForm.modelNo} onChange={e=>setAssetForm({...assetForm,modelNo:e.target.value})}/></label></div>
      <div className="form-grid two"><label>製造番号・シリアル<input value={assetForm.serialNo} onChange={e=>setAssetForm({...assetForm,serialNo:e.target.value})}/></label><label>保管場所<input value={assetForm.storageLocation} onChange={e=>setAssetForm({...assetForm,storageLocation:e.target.value})} placeholder="例：第一倉庫"/></label></div>
      <div className="form-grid three"><label>取得区分<select value={assetForm.acquisitionType} onChange={e=>setAssetForm({...assetForm,acquisitionType:e.target.value as AcquisitionType})}>{Object.entries(acquisitionLabel).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>取得日<input type="date" value={assetForm.acquisitionDate} onChange={e=>setAssetForm({...assetForm,acquisitionDate:e.target.value})}/></label><label>取得金額（円）<input type="number" min="0" step="1" value={assetForm.purchasePrice} onChange={e=>setAssetForm({...assetForm,purchasePrice:e.target.value})} placeholder="譲受は0または空欄"/></label></div>
      <div className="form-grid two"><label>燃料タイプ<select value={assetForm.fuelType} onChange={e=>setAssetForm({...assetForm,fuelType:e.target.value as FuelType})}>{Object.entries(fuelLabel).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>燃料メモ<input value={assetForm.fuelNote} onChange={e=>setAssetForm({...assetForm,fuelNote:e.target.value})} placeholder="例：50:1混合"/></label></div>
      <div className="form-grid two"><label>現在状態<select value={assetForm.status} onChange={e=>setAssetForm({...assetForm,status:e.target.value as EquipmentStatus})}>{Object.entries(statusLabel).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>次回整備日<input type="date" value={assetForm.nextMaintenanceDate} onChange={e=>setAssetForm({...assetForm,nextMaintenanceDate:e.target.value})}/></label></div>
      <label>破損・状態メモ<textarea value={assetForm.conditionNote} onChange={e=>setAssetForm({...assetForm,conditionNote:e.target.value})} placeholder="破損箇所、不調、注意点など"/></label>
      <div className="form-grid two"><label>走行距離（km）<input type="number" min="0" step="0.1" value={assetForm.currentOdometerKm} onChange={e=>setAssetForm({...assetForm,currentOdometerKm:e.target.value})}/></label><label>稼働時間（h）<input type="number" min="0" step="0.1" value={assetForm.currentHourMeter} onChange={e=>setAssetForm({...assetForm,currentHourMeter:e.target.value})}/></label></div>
      {assetForm.category==='VEHICLE'&&<div className="equipment-vehicle-form"><b>車両管理</b><div className="form-grid two"><label>車両番号<input value={assetForm.vehicleRegistrationNo} onChange={e=>setAssetForm({...assetForm,vehicleRegistrationNo:e.target.value})}/></label><label>車検期限<input type="date" value={assetForm.vehicleInspectionExpiry} onChange={e=>setAssetForm({...assetForm,vehicleInspectionExpiry:e.target.value})}/></label></div><div className="form-grid two"><label>税金期限<input type="date" value={assetForm.vehicleTaxDueDate} onChange={e=>setAssetForm({...assetForm,vehicleTaxDueDate:e.target.value})}/></label><label>保険期限<input type="date" value={assetForm.insuranceExpiry} onChange={e=>setAssetForm({...assetForm,insuranceExpiry:e.target.value})}/></label></div></div>}
      <label>備考<textarea value={assetForm.note} onChange={e=>setAssetForm({...assetForm,note:e.target.value})}/></label><label className="equipment-active"><input type="checkbox" checked={assetForm.active} onChange={e=>setAssetForm({...assetForm,active:e.target.checked})}/>現在使用している設備</label><div className="equipment-form-actions"><button type="button" className="secondary-button" onClick={()=>setAssetOpen(false)} disabled={busy}>キャンセル</button><button className="primary-button" disabled={busy}>{busy?'保存中…':'保存'}</button></div>
    </form></section></div>}

    {canManage&&recordOpen&&<div className="inventory-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)setRecordOpen(false)}}><section className="panel inventory-modal equipment-modal service-modal"><div className="section-head"><div><p className="eyebrow">SERVICE HISTORY</p><h2>{recordForm.id?'履歴を編集':'修理・整備履歴を登録'}</h2></div><button className="close-detail" onClick={()=>setRecordOpen(false)} disabled={busy}><X size={17}/></button></div><form className="equipment-form" onSubmit={submitRecord}>
      <div className="form-grid two"><label>対象設備<select required value={recordForm.equipmentId} onChange={e=>setRecordForm({...recordForm,equipmentId:e.target.value})}><option value="">選択してください</option>{assets.filter(a=>a.active).map(a=><option value={a.id} key={a.id}>{a.name}｜{a.assetNo}</option>)}</select></label><label>履歴区分<select value={recordForm.recordType} onChange={e=>setRecordForm({...recordForm,recordType:e.target.value as ServiceType})}>{Object.entries(serviceLabel).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label></div>
      <div className="form-grid three"><label>実施日<input required type="date" value={recordForm.recordDate} onChange={e=>setRecordForm({...recordForm,recordDate:e.target.value})}/></label><label>依頼先・購入先<input value={recordForm.vendor} onChange={e=>setRecordForm({...recordForm,vendor:e.target.value})}/></label><label>費用（円）<input type="number" min="0" step="1" value={recordForm.cost} onChange={e=>setRecordForm({...recordForm,cost:e.target.value})}/></label></div>
      <label>修理・整備内容<input required value={recordForm.description} onChange={e=>setRecordForm({...recordForm,description:e.target.value})} placeholder="例：Vベルト交換 / 車検 / 自動車税支払"/></label>
      <div className="form-grid three"><label>走行距離（km）<input type="number" min="0" step="0.1" value={recordForm.odometerKm} onChange={e=>setRecordForm({...recordForm,odometerKm:e.target.value})}/></label><label>稼働時間（h）<input type="number" min="0" step="0.1" value={recordForm.hourMeter} onChange={e=>setRecordForm({...recordForm,hourMeter:e.target.value})}/></label><label>次回期限<input type="date" value={recordForm.nextDueDate} onChange={e=>setRecordForm({...recordForm,nextDueDate:e.target.value})}/></label></div>
      <div className="form-grid two"><label>作業後の状態<select value={recordForm.statusAfter} onChange={e=>setRecordForm({...recordForm,statusAfter:e.target.value as EquipmentStatus|''})}><option value="">変更しない</option>{Object.entries(statusLabel).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>状態メモ<input value={recordForm.conditionAfter} onChange={e=>setRecordForm({...recordForm,conditionAfter:e.target.value})} placeholder="例：修理完了、正常動作"/></label></div>
      <label>備考<textarea value={recordForm.note} onChange={e=>setRecordForm({...recordForm,note:e.target.value})}/></label><div className="equipment-form-actions"><button type="button" className="secondary-button" onClick={()=>setRecordOpen(false)} disabled={busy}>キャンセル</button><button className="primary-button" disabled={busy}>{busy?'保存中…':'保存'}</button></div>
    </form></section></div>}
  </div>
}