import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { CalendarDays, Edit3, Plus, RefreshCw, Trash2, X } from 'lucide-react'
import { useAppPermissions } from '../lib/permissions'
import { deleteFertilizerPlan, loadFertilizerFields, loadFertilizerPlans, loadFertilizers, saveFertilizerPlan, type Fertilizer, type FertilizerField, type FertilizerPlan } from '../lib/fertilizers'

const yearNow=()=>Number(new Intl.DateTimeFormat('ja-JP-u-ca-iso8601',{year:'numeric'}).format(new Date()).replace(/\D/g,''))||new Date().getFullYear()
const blank={id:'',planYear:String(yearNow()),month:'2',period:'上旬',fieldId:'',allFields:true,purpose:'春肥',fertilizerId:'',rateKgPer10a:'',plannedDate:'',executedDate:'',status:'planned',note:''}
const statusLabel:Record<string,string>={planned:'予定',completed:'実施済',cancelled:'中止'}
export default function FertilizerPlansPage(){
 const{allowed}=useAppPermissions(),canManage=allowed('fertilizer_plans.manage')
 const[rows,setRows]=useState<FertilizerPlan[]>([]),[fertilizers,setFertilizers]=useState<Fertilizer[]>([]),[fields,setFields]=useState<FertilizerField[]>([]),[loading,setLoading]=useState(true),[form,setForm]=useState(blank),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(''),[year,setYear]=useState(String(yearNow()))
 async function refresh(){setLoading(true);setError('');try{const[r,f,fi]=await Promise.all([loadFertilizerPlans(),loadFertilizers(),loadFertilizerFields()]);setRows(r);setFertilizers(f.filter(x=>x.active));setFields(fi)}catch(e:any){setError(e?.message||'施肥計画を読み込めませんでした。')}finally{setLoading(false)}}useEffect(()=>{void refresh()},[])
 const filtered=useMemo(()=>rows.filter(r=>String(r.planYear)===year),[rows,year])
 function edit(r:FertilizerPlan){if(!canManage){setError('施肥計画を変更する権限がありません。');return}setForm({id:r.id,planYear:String(r.planYear),month:String(r.month),period:r.period||'',fieldId:r.fieldId||'',allFields:r.allFields,purpose:r.purpose,fertilizerId:r.fertilizerId||'',rateKgPer10a:r.rateKgPer10a===null?'':String(r.rateKgPer10a),plannedDate:r.plannedDate,executedDate:r.executedDate,status:r.status,note:r.note});setOpen(true)}
 async function submit(e:FormEvent){e.preventDefault();if(!canManage)return setError('施肥計画を変更する権限がありません。');setBusy(true);setError('');setSuccess('');try{await saveFertilizerPlan({id:form.id,planYear:Number(form.planYear),month:Number(form.month),period:form.period,fieldId:form.fieldId,allFields:form.allFields,purpose:form.purpose,fertilizerId:form.fertilizerId,rateKgPer10a:form.rateKgPer10a===''?null:Number(form.rateKgPer10a),plannedDate:form.plannedDate,executedDate:form.executedDate,status:form.status,note:form.note});setSuccess(form.id?'施肥計画を更新しました。':'施肥計画を追加しました。');setOpen(false);setYear(form.planYear);setForm(blank);await refresh()}catch(e:any){setError(e?.message||'施肥計画の保存に失敗しました。')}finally{setBusy(false)}}
 async function remove(r:FertilizerPlan){if(!canManage)return setError('施肥計画を削除する権限がありません。');if(!window.confirm(`${r.planYear}年${r.month}月の施肥計画を削除しますか？`))return;setBusy(true);try{await deleteFertilizerPlan(r.id);setSuccess('施肥計画を削除しました。');await refresh()}catch(e:any){setError(e?.message||'削除に失敗しました。')}finally{setBusy(false)}}
 return <div className="page fertilizer-page"><div className="page-head"><div><p className="eyebrow">FERTILIZER PLAN</p><h1>年間施肥計画</h1><p className="sub">春肥・芽出し肥・夏肥・秋肥などの年間計画を圃場別／全圃場で管理します。</p></div><div className="head-actions">{canManage&&<button className="primary-button" onClick={()=>{setForm({...blank,planYear:year});setOpen(true)}}><Plus size={17}/>計画を追加</button>}<button className="icon-button" onClick={()=>void refresh()}><RefreshCw size={18} className={loading?'spin':''}/></button></div></div>{error&&<div className="notice error dashboard-notice">{error}</div>}{success&&<div className="notice success dashboard-notice">{success}</div>}
 <div className="plan-year-tabs">{[yearNow()-1,yearNow(),yearNow()+1].map(y=><button key={y} className={year===String(y)?'active':''} onClick={()=>setYear(String(y))}>{y}年</button>)}</div>
 <section className="panel fertilizer-plan-panel"><div className="fertilizer-plan-list">{filtered.map(r=><article className={`fertilizer-plan-row status-${r.status}`} key={r.id}><div className="fertilizer-plan-date"><b>{r.month}月{r.period}</b><span>{r.plannedDate||'日付未指定'}</span></div><div className="fertilizer-plan-main"><div><h3>{r.purpose||'施肥'}</h3><span>{r.fieldName}</span></div><div className="fertilizer-plan-material"><b>{r.fertilizerName}</b><span>{r.rateKgPer10a===null?'施肥量未設定':`${r.rateKgPer10a} kg/10a`}</span></div>{r.note&&<p>{r.note}</p>}</div><div className="fertilizer-plan-side"><span className={`status-pill ${r.status}`}>{statusLabel[r.status]||r.status}</span>{r.executedDate&&<small>実施 {r.executedDate}</small>}{canManage&&<div><button onClick={()=>edit(r)}><Edit3 size={14}/>編集</button><button className="danger-text-button" onClick={()=>void remove(r)}><Trash2 size={14}/></button></div>}</div></article>)}{!loading&&!filtered.length&&<div className="empty-state-small"><CalendarDays size={24}/><span>{year}年の施肥計画はまだありません。</span></div>}</div></section>
 {open&&canManage&&<div className="inventory-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)setOpen(false)}}><section className="panel inventory-modal fertilizer-modal"><div className="section-head"><div><p className="eyebrow">FERTILIZER PLAN</p><h2>{form.id?'施肥計画を編集':'施肥計画を追加'}</h2></div><button className="close-detail" onClick={()=>setOpen(false)}><X size={17}/></button></div><form className="inventory-action-form" onSubmit={submit}><div className="form-grid three"><label>年<input type="number" min="2020" max="2100" value={form.planYear} onChange={e=>setForm({...form,planYear:e.target.value})}/></label><label>月<select value={form.month} onChange={e=>setForm({...form,month:e.target.value})}>{Array.from({length:12},(_,i)=>i+1).map(m=><option key={m} value={m}>{m}月</option>)}</select></label><label>時期<select value={form.period} onChange={e=>setForm({...form,period:e.target.value})}><option>上旬</option><option>中旬</option><option>下旬</option><option value="">指定なし</option></select></label></div><label className="check-line"><input type="checkbox" checked={form.allFields} onChange={e=>setForm({...form,allFields:e.target.checked})}/>全圃場を対象</label>{!form.allFields&&<label>対象圃場<select required value={form.fieldId} onChange={e=>setForm({...form,fieldId:e.target.value})}><option value="">選択</option>{fields.map(f=><option value={f.id} key={f.id}>{f.legacyId} {f.name}</option>)}</select></label>}<div className="form-grid two"><label>目的<input value={form.purpose} onChange={e=>setForm({...form,purpose:e.target.value})} placeholder="春肥 / 芽出し肥 / 夏肥 / 秋肥"/></label><label>肥料<select value={form.fertilizerId} onChange={e=>setForm({...form,fertilizerId:e.target.value})}><option value="">未指定</option>{fertilizers.map(f=><option value={f.id} key={f.id}>{f.name}</option>)}</select></label></div><div className="form-grid two"><label>予定施肥量（kg/10a）<input type="number" min="0" step="0.001" value={form.rateKgPer10a} onChange={e=>setForm({...form,rateKgPer10a:e.target.value})}/></label><label>予定日<input type="date" value={form.plannedDate} onChange={e=>setForm({...form,plannedDate:e.target.value})}/></label></div><div className="form-grid two"><label>状態<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="planned">予定</option><option value="completed">実施済</option><option value="cancelled">中止</option></select></label><label>実施日<input type="date" value={form.executedDate} onChange={e=>setForm({...form,executedDate:e.target.value})}/></label></div><label>備考<textarea rows={3} value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></label><button className="primary-button" disabled={busy}>{busy?'保存中…':'保存'}</button></form></section></div>}
 </div>
}
