import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { Beaker, Edit3, Plus, RefreshCw, Search, X } from 'lucide-react'
import { loadFertilizerRole, loadFertilizers, saveFertilizer, type Fertilizer } from '../lib/fertilizers'

const blank={id:'',name:'',manufacturer:'',category:'',n:'0',p:'0',k:'0',mg:'0',ca:'0',note:'',active:true}

export default function FertilizerMasterPage(){
  const[rows,setRows]=useState<Fertilizer[]>([]),[role,setRole]=useState(''),[loading,setLoading]=useState(true),[query,setQuery]=useState(''),[form,setForm]=useState(blank),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState('')
  async function refresh(){setLoading(true);setError('');try{const[r,ro]=await Promise.all([loadFertilizers(),loadFertilizerRole()]);setRows(r);setRole(ro)}catch(e:any){setError(e?.message||'肥料マスタを読み込めませんでした。')}finally{setLoading(false)}}
  useEffect(()=>{void refresh()},[])
  const filtered=useMemo(()=>{const q=query.trim().normalize('NFKC').toLowerCase();if(!q)return rows;return rows.filter(r=>`${r.name} ${r.manufacturer} ${r.category} ${r.legacyId}`.normalize('NFKC').toLowerCase().includes(q))},[rows,query])
  function edit(r:Fertilizer){setForm({id:r.id,name:r.name,manufacturer:r.manufacturer,category:r.category,n:String(r.n),p:String(r.p),k:String(r.k),mg:String(r.mg),ca:String(r.ca),note:r.note,active:r.active});setOpen(true);setError('');setSuccess('')}
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');setSuccess('');try{for(const[v,label]of[[form.n,'窒素'],[form.p,'リン酸'],[form.k,'加里'],[form.mg,'苦土'],[form.ca,'石灰']] as const){const x=Number(v);if(!Number.isFinite(x)||x<0||x>100)throw new Error(`${label}成分は0〜100%で入力してください。`)}await saveFertilizer({id:form.id||undefined,name:form.name,manufacturer:form.manufacturer,category:form.category,n:Number(form.n),p:Number(form.p),k:Number(form.k),mg:Number(form.mg),ca:Number(form.ca),note:form.note,active:form.active});setSuccess(form.id?'肥料マスタを更新しました。':'肥料マスタへ追加しました。');setOpen(false);setForm(blank);await refresh()}catch(e:any){setError(e?.message||'保存に失敗しました。')}finally{setBusy(false)}}
  const isAdmin=role==='admin'
  return <div className="page fertilizer-page">
    <div className="page-head"><div><p className="eyebrow">FERTILIZER</p><h1>肥料マスタ</h1><p className="sub">肥料の商品情報とN・P・K成分を管理します。施肥時の成分投入量はここから自動計算されます。</p></div><div className="head-actions">{isAdmin&&<button className="primary-button" onClick={()=>{setForm(blank);setOpen(true)}}><Plus size={17}/>肥料を追加</button>}<button className="icon-button" onClick={()=>void refresh()} disabled={loading}><RefreshCw size={18} className={loading?'spin':''}/></button></div></div>
    {error&&<div className="notice error dashboard-notice">{error}</div>}{success&&<div className="notice success dashboard-notice">{success}</div>}
    <section className="panel"><div className="toolbar"><div className="search-box"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="肥料名・メーカー・種類を検索"/></div><span className="muted">{filtered.length}件</span></div>
      <div className="fertilizer-master-grid">{filtered.map(r=><article className={`fertilizer-master-card ${!r.active?'inactive':''}`} key={r.id}><div className="fertilizer-card-head"><div><span>{r.category||'種類未設定'}</span><h3>{r.name}</h3><small>{r.manufacturer||'メーカー未設定'}</small></div><Beaker size={22}/></div><div className="npk-strip"><div><span>N</span><b>{r.n}%</b></div><div><span>P</span><b>{r.p}%</b></div><div><span>K</span><b>{r.k}%</b></div></div><div className="secondary-nutrients"><span>Mg {r.mg}%</span><span>Ca {r.ca}%</span></div>{r.note&&<p>{r.note}</p>}<div className="fertilizer-card-foot"><code>{r.legacyId}</code>{isAdmin&&<button onClick={()=>edit(r)}><Edit3 size={14}/>編集</button>}</div></article>)}{!loading&&!filtered.length&&<p className="empty">肥料マスタはまだありません。</p>}</div>
    </section>
    {open&&<div className="inventory-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)setOpen(false)}}><section className="panel inventory-modal fertilizer-modal"><div className="section-head"><div><p className="eyebrow">FERTILIZER MASTER</p><h2>{form.id?'肥料を編集':'肥料を追加'}</h2></div><button className="close-detail" onClick={()=>setOpen(false)} disabled={busy}><X size={17}/></button></div><form className="inventory-action-form" onSubmit={submit}><label>肥料名<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="例：コーポしき島9号"/></label><div className="form-grid two"><label>メーカー<input value={form.manufacturer} onChange={e=>setForm({...form,manufacturer:e.target.value})}/></label><label>種類<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option value="">選択</option><option>化成肥料</option><option>配合肥料</option><option>有機質肥料</option><option>液肥</option><option>土壌改良資材</option><option>その他</option></select></label></div><div className="npk-form-grid"><label>N 窒素（%）<input type="number" min="0" max="100" step="0.001" value={form.n} onChange={e=>setForm({...form,n:e.target.value})}/></label><label>P リン酸（%）<input type="number" min="0" max="100" step="0.001" value={form.p} onChange={e=>setForm({...form,p:e.target.value})}/></label><label>K 加里（%）<input type="number" min="0" max="100" step="0.001" value={form.k} onChange={e=>setForm({...form,k:e.target.value})}/></label></div><div className="form-grid two"><label>Mg 苦土（%）<input type="number" min="0" max="100" step="0.001" value={form.mg} onChange={e=>setForm({...form,mg:e.target.value})}/></label><label>Ca 石灰（%）<input type="number" min="0" max="100" step="0.001" value={form.ca} onChange={e=>setForm({...form,ca:e.target.value})}/></label></div><label>備考<textarea rows={3} value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></label><label className="check-line"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/>使用中の肥料として表示</label><button className="primary-button" disabled={busy}>{busy?'保存中…':'保存'}</button></form></section></div>}
  </div>
}
