import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { Link, useNavigate, useSearchParams } from 'react-router-dom'
import { CalendarDays, Edit3, History, RefreshCw, Trash2, X } from 'lucide-react'
import { useAppPermissions } from '../lib/permissions'
import { deleteFertilizerApplication, loadFertilizerApplication, loadFertilizerApplications, loadFertilizerFields, loadFertilizerLots, loadFertilizers, registerFertilizerApplication, updateFertilizerApplication, type Fertilizer, type FertilizerApplication, type FertilizerField, type FertilizerLot } from '../lib/fertilizers'

const today=()=>new Intl.DateTimeFormat('sv-SE').format(new Date());const num=new Intl.NumberFormat('ja-JP',{maximumFractionDigits:3})
export default function FertilizerApplicationPage(){
 const{allowed}=useAppPermissions(),canCreate=allowed('fertilizer_applications.create'),canEdit=allowed('fertilizer_applications.edit'),canDelete=allowed('fertilizer_applications.delete')
 const navigate=useNavigate(),[searchParams]=useSearchParams();const editParam=searchParams.get('edit')||''
 const[fertilizers,setFertilizers]=useState<Fertilizer[]>([]),[lots,setLots]=useState<FertilizerLot[]>([]),[fields,setFields]=useState<FertilizerField[]>([]),[history,setHistory]=useState<FertilizerApplication[]>([]),[editing,setEditing]=useState<FertilizerApplication|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState('')
 const[date,setDate]=useState(today()),[operator,setOperator]=useState(''),[method,setMethod]=useState('株元・畝間施用'),[weather,setWeather]=useState(''),[note,setNote]=useState(''),[fertilizerId,setFertilizerId]=useState(''),[lotId,setLotId]=useState(''),[rate,setRate]=useState('40'),[selectedFields,setSelectedFields]=useState<string[]>([])

 function resetForm(){setEditing(null);setDate(today());setOperator('');setMethod('株元・畝間施用');setWeather('');setNote('');setFertilizerId('');setLotId('');setRate('40');setSelectedFields([])}
 function applyEdit(a:FertilizerApplication){
   if(!canEdit)throw new Error('施肥記録を編集する権限がありません。')
   if(!a.lines.length)throw new Error('施肥明細がないため編集できません。')
   const first=a.lines[0];const uniform=a.lines.every(l=>l.fertilizerId===first.fertilizerId&&l.lotId===first.lotId&&Math.abs(l.rateKgPer10a-first.rateKgPer10a)<0.02)
   if(!uniform)throw new Error('複数の肥料・ロット・施肥量が混在する旧記録は、この簡易編集画面では編集できません。履歴詳細を確認してください。')
   setEditing(a);setDate(a.date);setOperator(a.operator);setMethod(a.method||'株元・畝間施用');setWeather(a.weather);setNote(a.note);setFertilizerId(first.fertilizerId);setLotId(first.lotId);setRate(String(first.rateKgPer10a));setSelectedFields(a.lines.map(l=>l.fieldId));window.scrollTo({top:0,behavior:'smooth'})
 }
 async function refresh(){setLoading(true);setError('');try{const[f,l,fi,h]=await Promise.all([loadFertilizers(),loadFertilizerLots(),loadFertilizerFields(),loadFertilizerApplications(5)]);setFertilizers(f.filter(x=>x.active));setLots(l);setFields(fi);setHistory(h);if(editParam){if(!canEdit)throw new Error('施肥記録を編集する権限がありません。');const a=await loadFertilizerApplication(editParam);if(!a)throw new Error('編集する施肥記録が見つかりません。');applyEdit(a)}}catch(e:any){setError(e?.message||'施肥データを読み込めませんでした。')}finally{setLoading(false)}} useEffect(()=>{void refresh()},[editParam,canEdit])

 const editOldByLot=useMemo(()=>{const m=new Map<string,number>();for(const l of editing?.lines||[])m.set(l.lotId,(m.get(l.lotId)||0)+l.amountKg);return m},[editing])
 const availableLots=lots.filter(l=>l.fertilizerId===fertilizerId&&(l.balanceKg>0||editOldByLot.has(l.id)))
 const selectedLot=lots.find(l=>l.id===lotId);const virtualBalance=(selectedLot?.balanceKg||0)+(editOldByLot.get(lotId)||0)
 const fertilizer=fertilizers.find(f=>f.id===fertilizerId);const rateNum=Number(rate||0)
 const preview=useMemo(()=>selectedFields.map(id=>fields.find(f=>f.id===id)).filter(Boolean).map(f=>{const amount=(f!.areaM2/1000)*rateNum;return{field:f!,amount,n:amount*(fertilizer?.n||0)/100,p:amount*(fertilizer?.p||0)/100,k:amount*(fertilizer?.k||0)/100}}),[selectedFields,fields,rateNum,fertilizer]);const total=preview.reduce((s,x)=>s+x.amount,0),nTotal=preview.reduce((s,x)=>s+x.n,0),pTotal=preview.reduce((s,x)=>s+x.p,0),kTotal=preview.reduce((s,x)=>s+x.k,0),shortage=!!selectedLot&&total>virtualBalance+0.0001
 function toggleField(id:string){setSelectedFields(old=>old.includes(id)?old.filter(x=>x!==id):[...old,id])}
 async function submit(e:FormEvent){e.preventDefault();if(editing?!canEdit:!canCreate)return setError(editing?'施肥記録を編集する権限がありません。':'施肥を登録する権限がありません。');setBusy(true);setError('');setSuccess('');try{if(!fertilizerId||!lotId)throw new Error('肥料と在庫ロットを選択してください。');if(rateNum<=0)throw new Error('施肥量kg/10aを入力してください。');if(!selectedFields.length)throw new Error('圃場を選択してください。');if(shortage)throw new Error('肥料在庫が不足しています。');const payload={date,operator,method,weather,note,lines:preview.map(x=>({fertilizerId,lotId,fieldId:x.field.id,amountKg:Number(x.amount.toFixed(3))}))};if(editing){await updateFertilizerApplication(editing.id,payload);setSuccess(`${editing.legacyId} を更新しました。在庫は差分だけ反映しています。`);resetForm();navigate('/fertilizer-applications',{replace:true})}else{await registerFertilizerApplication(payload);setSuccess('施肥記録を登録し、肥料在庫とN/P/K投入量へ反映しました。');setSelectedFields([]);setNote('')}await refresh()}catch(e:any){setError(e?.message||'施肥登録に失敗しました。')}finally{setBusy(false)}}
 async function remove(a:FertilizerApplication){if(!canDelete)return setError('施肥記録を削除する権限がありません。');const reason=window.prompt('削除理由を入力してください。削除すると使用肥料は在庫へ戻入されます。','入力誤り');if(reason===null)return;setBusy(true);try{await deleteFertilizerApplication(a.id,reason);setSuccess('施肥記録を削除し、肥料を在庫へ戻しました。');await refresh()}catch(e:any){setError(e?.message||'削除に失敗しました。')}finally{setBusy(false)}}
 function cancelEdit(){resetForm();navigate('/fertilizer-applications',{replace:true})}
 const grouped=useMemo(()=>{const m=new Map<string,FertilizerField[]>();for(const f of fields){const key=f.location||'その他';m.set(key,[...(m.get(key)||[]),f])}return [...m.entries()]},[fields])
 const canShowForm=editing?canEdit:canCreate
 return <div className="page fertilizer-page"><div className="page-head"><div><p className="eyebrow">FERTILIZATION</p><h1>施肥</h1><p className="sub">圃場面積とkg/10aから必要量を計算し、在庫・N/P/K投入量へ同時反映します。</p></div><div className="head-actions"><Link className="secondary-button compact" to="/fertilizer-history"><History size={16}/>施肥履歴</Link><button className="icon-button" onClick={()=>void refresh()} disabled={loading}><RefreshCw size={18} className={loading?'spin':''}/></button></div></div>{error&&<div className="notice error dashboard-notice">{error}</div>}{success&&<div className="notice success dashboard-notice">{success}</div>}
 {editing&&<div className="fertilizer-edit-banner"><Edit3 size={18}/><div><b>{editing.legacyId} を編集中</b><span>編集前の使用量を一時的に在庫へ戻した状態で不足判定し、保存時は差分だけ入出庫履歴へ追加します。</span></div><button type="button" onClick={cancelEdit}><X size={16}/>編集をやめる</button></div>}
 {canShowForm?<div className="fertilizer-application-layout"><form className="panel fertilizer-application-form" onSubmit={submit}><h2>{editing?'施肥記録を編集':'施肥を登録'}</h2><div className="form-grid three"><label>施肥日<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>担当者<input value={operator} onChange={e=>setOperator(e.target.value)} placeholder="未入力ならログイン名"/></label><label>天候<input value={weather} onChange={e=>setWeather(e.target.value)} placeholder="晴れ / 曇り"/></label></div><div className="form-grid two"><label>肥料<select required value={fertilizerId} onChange={e=>{setFertilizerId(e.target.value);setLotId('')}}><option value="">選択してください</option>{fertilizers.map(f=><option value={f.id} key={f.id}>{f.name}（N{f.n}-P{f.p}-K{f.k}）</option>)}</select></label><label>在庫ロット<select required value={lotId} onChange={e=>setLotId(e.target.value)} disabled={!fertilizerId}><option value="">選択してください</option>{availableLots.map(l=><option value={l.id} key={l.id}>{l.legacyId}｜{editing&&editOldByLot.has(l.id)?`編集時利用可 ${num.format(l.balanceKg+(editOldByLot.get(l.id)||0))}kg`:`残 ${num.format(l.balanceKg)}kg`}</option>)}</select></label></div><div className="form-grid two"><label>施肥量（kg / 10a）<input type="number" min="0.001" step="0.001" value={rate} onChange={e=>setRate(e.target.value)}/></label><label>施肥方法<input value={method} onChange={e=>setMethod(e.target.value)}/></label></div>
 <div className="fertilizer-field-select"><div className="section-head"><div><h3>対象圃場</h3><p className="muted">圃場カードをタップして選択</p></div><span>{selectedFields.length}圃場</span></div>{grouped.map(([loc,fs])=><div className="fertilizer-field-group" key={loc}><b>{loc}</b><div>{fs.map(f=>{const checked=selectedFields.includes(f.id);return <button type="button" className={checked?'selected':''} onClick={()=>toggleField(f.id)} key={f.id}><span>{f.legacyId}</span><strong>{f.name}</strong><small>{num.format(f.areaM2)}m² / {(f.areaM2/1000).toFixed(3)}反</small></button>})}</div></div>)}</div><label>備考<textarea rows={2} value={note} onChange={e=>setNote(e.target.value)}/></label><div className="fertilizer-application-summary"><div><span>必要肥料</span><b className={shortage?'danger-text':''}>{num.format(total)}kg</b><small>{selectedLot?`${editing?'編集時利用可':'在庫'} ${num.format(virtualBalance)}kg`:'ロット未選択'}</small></div><div><span>N投入</span><b>{num.format(nTotal)}kg</b></div><div><span>P投入</span><b>{num.format(pTotal)}kg</b></div><div><span>K投入</span><b>{num.format(kTotal)}kg</b></div></div>{shortage&&<div className="notice error">在庫不足です。別ロットまたは施肥量を確認してください。</div>}<button className="primary-button fertilizer-submit" disabled={busy||shortage}>{busy?(editing?'更新中…':'登録中…'):(editing?'施肥記録を更新':'施肥を登録')}</button></form>
 <aside className="panel fertilizer-preview"><h2>圃場別プレビュー</h2>{preview.map(x=><div className="fertilizer-preview-row" key={x.field.id}><div><b>{x.field.legacyId} {x.field.name}</b><span>{num.format(x.field.areaM2)}m²</span></div><strong>{num.format(x.amount)}kg</strong><small>N {num.format(x.n)} / P {num.format(x.p)} / K {num.format(x.k)} kg</small></div>)}{!preview.length&&<p className="empty">圃場を選択すると必要量を表示します。</p>}</aside></div>:<section className="panel"><p className="empty">施肥記録は閲覧のみ許可されています。新規登録には権限設定が必要です。</p></section>}
 <section className="panel fertilizer-history"><div className="panel-title"><div><h2>直近の施肥</h2><p>最新5件。検索・集計は施肥履歴へ。</p></div><Link className="panel-link" to="/fertilizer-history">履歴を開く<CalendarDays size={14}/></Link></div><div className="fertilizer-history-list">{history.map(a=><article key={a.id}><div className="fertilizer-history-head"><div><span>{a.date}</span><b>{a.legacyId}</b><small>{a.operator||'担当未入力'} / {a.method||'方法未入力'}</small></div><div><strong>{num.format(a.totalKg)}kg</strong>{canEdit&&<button onClick={()=>navigate(`/fertilizer-applications?edit=${a.id}`)}><Edit3 size={14}/>編集</button>}{canDelete&&<button disabled={busy} className="danger-text-button" onClick={()=>void remove(a)}><Trash2 size={14}/>削除</button>}</div></div><div className="fertilizer-history-npk"><span>N <b>{num.format(a.nKg)}kg</b></span><span>P <b>{num.format(a.pKg)}kg</b></span><span>K <b>{num.format(a.kKg)}kg</b></span></div><div className="fertilizer-history-lines">{a.lines.map(l=><span key={l.id}>{l.fieldLegacyId} {l.fieldName}｜{l.fertilizerName} {num.format(l.amountKg)}kg（{num.format(l.rateKgPer10a)}kg/10a）</span>)}</div></article>)}{!loading&&!history.length&&<p className="empty">施肥履歴はまだありません。</p>}</div></section>
 </div>
}