import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { Beaker, Database, Download, Edit3, ExternalLink, Plus, RefreshCw, Search, ShieldCheck, X } from 'lucide-react'
import { useAppPermissions } from '../lib/permissions'
import { loadFertilizers, loadOfficialFertilizerMeta, saveFertilizer, searchOfficialFertilizers, syncOfficialFertilizers, type Fertilizer, type OfficialFertilizer, type OfficialFertilizerMeta } from '../lib/fertilizers'

const blank={id:'',officialId:'',name:'',manufacturer:'',category:'',n:'0',p:'0',k:'0',mg:'0',ca:'0',note:'',active:true}
const emptyMeta:OfficialFertilizerMeta={count:0,sourceDate:'',rowCount:0,completedAt:''}
const nf=new Intl.NumberFormat('ja-JP')
const pct=(v:number)=>Number.isInteger(v)?String(v):String(Math.round(v*1000)/1000)

export default function FertilizerMasterPage(){
  const{allowed}=useAppPermissions(),canManage=allowed('fertilizers.manage'),canSync=allowed('fertilizers.sync')
  const[rows,setRows]=useState<Fertilizer[]>([]),[loading,setLoading]=useState(true),[query,setQuery]=useState(''),[form,setForm]=useState(blank),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState('')
  const[tab,setTab]=useState<'master'|'official'>('master'),[officialRows,setOfficialRows]=useState<OfficialFertilizer[]>([]),[officialMeta,setOfficialMeta]=useState<OfficialFertilizerMeta>(emptyMeta),[officialQuery,setOfficialQuery]=useState(''),[officialLoading,setOfficialLoading]=useState(false),[syncing,setSyncing]=useState(false)

  async function refresh(){setLoading(true);setError('');try{const[r,m]=await Promise.all([loadFertilizers(),loadOfficialFertilizerMeta()]);setRows(r);setOfficialMeta(m)}catch(e:any){setError(e?.message||'肥料マスタを読み込めませんでした。')}finally{setLoading(false)}}
  async function loadOfficial(q=officialQuery){setOfficialLoading(true);setError('');try{const[r,m]=await Promise.all([searchOfficialFertilizers(q.trim(),100,0),loadOfficialFertilizerMeta()]);setOfficialRows(r);setOfficialMeta(m)}catch(e:any){setError(e?.message||'公式肥料DBを検索できませんでした。')}finally{setOfficialLoading(false)}}
  useEffect(()=>{void refresh()},[])
  useEffect(()=>{if(tab==='official'&&!officialLoading&&officialRows.length===0&&officialMeta.count>0)void loadOfficial('')},[tab,officialMeta.count])

  const filtered=useMemo(()=>{const q=query.trim().normalize('NFKC').toLowerCase();if(!q)return rows;return rows.filter(r=>`${r.name} ${r.manufacturer} ${r.category} ${r.legacyId} ${r.officialRegistrationNo}`.normalize('NFKC').toLowerCase().includes(q))},[rows,query])
  const linkedIds=useMemo(()=>new Set(rows.map(r=>r.officialRegistrationId).filter(Boolean)),[rows])
  const linkedRegs=useMemo(()=>new Set(rows.map(r=>r.officialRegistrationNo).filter(Boolean)),[rows])

  function edit(r:Fertilizer){if(!canManage){setError('肥料マスタを編集する権限がありません。');return}setForm({id:r.id,officialId:r.officialRegistrationId,name:r.name,manufacturer:r.manufacturer,category:r.category,n:String(r.n),p:String(r.p),k:String(r.k),mg:String(r.mg),ca:String(r.ca),note:r.note,active:r.active});setOpen(true);setError('');setSuccess('')}
  function importOfficial(r:OfficialFertilizer){
    if(!canManage){setError('公式DBから肥料マスタへ登録する権限がありません。');return}
    if(r.lapseStatus){setError(`${r.registrationNo||r.name} は「${r.lapseStatus}」のため、公式DBから使用中マスタへ直接登録できません。`);return}
    const source=[r.registrationNo&&`登録番号 ${r.registrationNo}`,r.sourceDate&&`公式DB同期 ${r.sourceDate}`].filter(Boolean).join(' / ')
    setForm({id:'',officialId:r.id,name:r.name,manufacturer:r.company,category:r.type,n:String(r.n),p:String(r.p),k:String(r.k),mg:String(r.mg),ca:String(r.ca),note:source?`農林水産省 肥料登録銘柄検索から取込（${source}）`:'農林水産省 肥料登録銘柄検索から取込',active:true});setOpen(true);setError('');setSuccess('')
  }
  async function submit(e:FormEvent){e.preventDefault();if(!canManage)return setError('肥料マスタを変更する権限がありません。');setBusy(true);setError('');setSuccess('');try{for(const[v,label]of[[form.n,'窒素'],[form.p,'リン酸'],[form.k,'加里'],[form.mg,'苦土'],[form.ca,'石灰']] as const){const x=Number(v);if(!Number.isFinite(x)||x<0||x>100)throw new Error(`${label}成分は0〜100%で入力してください。`)}await saveFertilizer({id:form.id||undefined,name:form.name,manufacturer:form.manufacturer,category:form.category,n:Number(form.n),p:Number(form.p),k:Number(form.k),mg:Number(form.mg),ca:Number(form.ca),note:form.note,active:form.active,officialRegistrationId:form.officialId||undefined});setSuccess(form.id?'肥料マスタを更新しました。':'肥料マスタへ追加しました。');setOpen(false);setForm(blank);await refresh()}catch(e:any){setError(e?.message||'保存に失敗しました。')}finally{setBusy(false)}}
  async function runSync(){
    if(!canSync)return setError('公式肥料DBを同期する権限がありません。')
    if(!window.confirm('農林水産省の肥料登録データ（全件）を取得して公式DBを更新します。数十秒〜数分かかる場合があります。実行しますか？'))return
    setSyncing(true);setError('');setSuccess('')
    try{const r=await syncOfficialFertilizers();setSuccess(`公式肥料DBを同期しました：${nf.format(r.rows)}件 / ${r.sourceDate}`);setOfficialQuery('');await Promise.all([refresh(),loadOfficial('')])}catch(e:any){setError(e?.message||'公式肥料DBの同期に失敗しました。')}finally{setSyncing(false)}
  }
  return <div className="page fertilizer-page">
    <div className="page-head"><div><p className="eyebrow">FERTILIZER</p><h1>肥料マスタ</h1><p className="sub">自社で使用する肥料と、農林水産省「肥料登録銘柄検索」の公式登録データを分けて管理します。</p></div><div className="head-actions">{tab==='master'&&canManage&&<button className="primary-button" onClick={()=>{setForm(blank);setOpen(true)}}><Plus size={17}/>肥料を追加</button>}{tab==='official'&&canSync&&<button className="primary-button" onClick={()=>void runSync()} disabled={syncing}><Download size={17}/>{syncing?'同期中…':'公式DB同期'}</button>}<button className="icon-button" onClick={()=>tab==='master'?void refresh():void loadOfficial()} disabled={loading||officialLoading||syncing}><RefreshCw size={18} className={loading||officialLoading?'spin':''}/></button></div></div>
    {error&&<div className="notice error dashboard-notice">{error}</div>}{success&&<div className="notice success dashboard-notice">{success}</div>}

    <div className="fertilizer-source-tabs"><button className={tab==='master'?'active':''} onClick={()=>setTab('master')}><Beaker size={17}/>自社肥料マスタ <span>{rows.length}</span></button><button className={tab==='official'?'active':''} onClick={()=>setTab('official')}><Database size={17}/>農水省 公式肥料DB <span>{officialMeta.count?nf.format(officialMeta.count):'—'}</span></button></div>

    {tab==='master'?<section className="panel"><div className="toolbar"><div className="search-box"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="肥料名・メーカー・種類・登録番号を検索"/></div><span className="muted">{filtered.length}件</span></div>
      <div className="fertilizer-master-grid">{filtered.map(r=><article className={`fertilizer-master-card ${!r.active?'inactive':''}`} key={r.id}><div className="fertilizer-card-head"><div><span>{r.category||'種類未設定'}</span><h3>{r.name}</h3><small>{r.manufacturer||'メーカー未設定'}</small></div><Beaker size={22}/></div><div className="npk-strip"><div><span>N</span><b>{r.n}%</b></div><div><span>P</span><b>{r.p}%</b></div><div><span>K</span><b>{r.k}%</b></div></div><div className="secondary-nutrients"><span>Mg {r.mg}%</span><span>Ca {r.ca}%</span></div>{r.officialRegistrationNo&&<div className="official-link-badge"><ShieldCheck size={14}/><span>公式登録 {r.officialRegistrationNo}</span>{r.officialSourceDate&&<small>{r.officialSourceDate}</small>}</div>}{r.note&&<p>{r.note}</p>}<div className="fertilizer-card-foot"><code>{r.legacyId}</code>{canManage&&<button onClick={()=>edit(r)}><Edit3 size={14}/>編集</button>}</div></article>)}{!loading&&!filtered.length&&<p className="empty">肥料マスタはまだありません。</p>}</div>
    </section>:<section className="panel official-fertilizer-panel">
      <div className="official-db-head"><div><div className="official-db-title"><ShieldCheck size={20}/><div><h2>農林水産省 肥料登録銘柄検索</h2><p>登録肥料の公式データです。自社で使用する肥料だけを「マスタへ登録」してください。</p></div></div><div className="official-db-meta"><span>登録データ <b>{nf.format(officialMeta.count)}件</b></span><span>最終同期 <b>{officialMeta.sourceDate||'未同期'}</b></span></div></div><a href="https://fertilizer-search.maff.go.jp/FertilizerRegistrationSearch" target="_blank" rel="noreferrer">公式サイト<ExternalLink size={14}/></a></div>
      <form className="toolbar official-fertilizer-toolbar" onSubmit={e=>{e.preventDefault();void loadOfficial(officialQuery)}}><div className="search-box"><Search size={17}/><input value={officialQuery} onChange={e=>setOfficialQuery(e.target.value)} placeholder="肥料名・会社名・種類・登録番号を検索"/></div><button className="secondary-button" disabled={officialLoading}>{officialLoading?'検索中…':'検索'}</button></form>
      {!officialMeta.count&&!officialLoading?<div className="official-empty"><Database size={30}/><h3>公式肥料DBはまだ同期されていません</h3><p>{canSync?'「公式DB同期」を実行すると、農林水産省の全件CSVを取得します。':'公式DB同期は権限を持つユーザーが実行できます。'}</p></div>:<div className="official-fertilizer-list">{officialRows.map(r=>{const imported=linkedIds.has(r.id)||(r.registrationNo&&linkedRegs.has(r.registrationNo));const expired=!!r.lapseStatus;const comps=Object.entries(r.components).filter(([,v])=>Number.isFinite(v)).slice(0,14);return <article className={`official-fertilizer-card ${expired?'expired':''}`} key={r.id}><div className="official-fertilizer-card-head"><div><div className="official-tags">{r.registrationCategory&&<span>{r.registrationCategory}</span>}{r.registrationNo&&<code>{r.registrationNo}</code>}{expired?<em>{r.lapseStatus}</em>:<span>有効</span>}</div><h3>{r.name}</h3><p>{r.company||'会社名未登録'}{r.type&&` / ${r.type}`}</p></div>{canManage&&<button className={imported?'imported':''} disabled={!!imported||expired} onClick={()=>importOfficial(r)}>{imported?<><ShieldCheck size={15}/>登録済</>:expired?<>失効</>:<><Plus size={15}/>マスタへ登録</>}</button>}</div><div className="official-npk"><div><span>N</span><b>{pct(r.n)}%</b></div><div><span>P</span><b>{pct(r.p)}%</b></div><div><span>K</span><b>{pct(r.k)}%</b></div><div><span>Mg</span><b>{pct(r.mg)}%</b></div><div><span>Ca</span><b>{pct(r.ca)}%</b></div></div>{comps.length>0&&<div className="official-components">{comps.map(([k,v])=><span key={k}><b>{k}</b> {pct(v)}%</span>)}</div>}<div className="official-fertilizer-detail"><span>登録日 <b>{r.registrationDate||'—'}</b></span><span>登録状況 <b>{r.lapseStatus||'有効'}</b></span>{r.address&&<span>所在地 <b>{r.address}</b></span>}</div></article>})}{!officialLoading&&!officialRows.length&&officialMeta.count>0&&<p className="empty">該当する公式肥料はありません。</p>}</div>}
      {officialRows.length>=100&&<p className="official-result-note">最大100件を表示しています。肥料名・会社名・登録番号で絞り込んでください。</p>}
    </section>}

    {open&&canManage&&<div className="inventory-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)setOpen(false)}}><section className="panel inventory-modal fertilizer-modal"><div className="section-head"><div><p className="eyebrow">FERTILIZER MASTER</p><h2>{form.id?'肥料を編集':form.officialId?'公式DBから肥料を登録':'肥料を追加'}</h2></div><button className="close-detail" onClick={()=>setOpen(false)} disabled={busy}><X size={17}/></button></div>{form.officialId&&<div className="official-import-notice"><ShieldCheck size={18}/><div><b>農水省公式データから入力しています</b><span>成分値は公式保証成分を優先して自動転記しています。実際に使用する商品の保証票も確認してください。</span></div></div>}<form className="inventory-action-form" onSubmit={submit}><label>肥料名<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="例：コーポしき島9号"/></label><div className="form-grid two"><label>メーカー<input value={form.manufacturer} onChange={e=>setForm({...form,manufacturer:e.target.value})}/></label><label>種類<input list="fertilizer-category-options" value={form.category} onChange={e=>setForm({...form,category:e.target.value})} placeholder="例：化成肥料"/><datalist id="fertilizer-category-options"><option value="化成肥料"/><option value="配合肥料"/><option value="有機質肥料"/><option value="液肥"/><option value="土壌改良資材"/><option value="その他"/></datalist></label></div><div className="npk-form-grid"><label>N 窒素（%）<input type="number" min="0" max="100" step="0.001" value={form.n} onChange={e=>setForm({...form,n:e.target.value})}/></label><label>P リン酸（%）<input type="number" min="0" max="100" step="0.001" value={form.p} onChange={e=>setForm({...form,p:e.target.value})}/></label><label>K 加里（%）<input type="number" min="0" max="100" step="0.001" value={form.k} onChange={e=>setForm({...form,k:e.target.value})}/></label></div><div className="form-grid two"><label>Mg 苦土（%）<input type="number" min="0" max="100" step="0.001" value={form.mg} onChange={e=>setForm({...form,mg:e.target.value})}/></label><label>Ca 石灰（%）<input type="number" min="0" max="100" step="0.001" value={form.ca} onChange={e=>setForm({...form,ca:e.target.value})}/></label></div><label>備考<textarea rows={3} value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></label><label className="check-line"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/>使用中の肥料として表示</label><button className="primary-button" disabled={busy}>{busy?'保存中…':'保存'}</button></form></section></div>}
  </div>
}