import { useEffect, useMemo, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { ArrowLeft, CalendarDays, Factory, Leaf, MapPinned, RefreshCw, Scissors, ShoppingCart, SprayCan } from 'lucide-react'
import { useAppPermissions } from '../lib/permissions'
import { loadFieldDossier, type DossierEvent, type FieldDossier } from '../lib/fieldDossier'
import { loadFieldSalesTrace, type FieldSalesTraceData } from '../lib/fieldSalesTrace'

const currentYear=()=>Number(new Intl.DateTimeFormat('en',{year:'numeric'}).format(new Date()))
const num=new Intl.NumberFormat('ja-JP',{maximumFractionDigits:3})
const yen=new Intl.NumberFormat('ja-JP',{style:'currency',currency:'JPY',maximumFractionDigits:0})
function label(type:DossierEvent['type']){if(type==='spray')return'散布';if(type==='fertilizer')return'施肥';if(type==='spray_plan')return'防除計画';if(type==='fertilizer_plan')return'施肥計画';if(type==='harvest_actual')return'摘採実績';if(type==='processing')return'製茶実績';return'摘採予定'}
function icon(type:DossierEvent['type']){if(type==='spray'||type==='spray_plan')return <SprayCan size={18}/>;if(type==='fertilizer'||type==='fertilizer_plan')return <Leaf size={18}/>;if(type==='harvest_actual')return <Scissors size={18}/>;if(type==='processing')return <Factory size={18}/>;return <CalendarDays size={18}/>}
export default function FieldDossierPage(){
 const{allowed}=useAppPermissions(),canRecordHarvest=allowed('harvest_processing.manage'),canViewSales=allowed('sales.view')
 const{fieldId}=useParams();const navigate=useNavigate();const[year,setYear]=useState(currentYear()),[data,setData]=useState<FieldDossier|null>(null),[sales,setSales]=useState<FieldSalesTraceData|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('')
 async function refresh(y=year){if(!fieldId)return;setLoading(true);setError('');try{const d=await loadFieldDossier(fieldId,y);setData(d);if(canViewSales)setSales(await loadFieldSalesTrace(fieldId,y));else setSales(null)}catch(e:any){setError(e?.message||'圃場カルテを読み込めませんでした。')}finally{setLoading(false)}}
 useEffect(()=>{void refresh(year)},[fieldId,year,canViewSales])
 const years=useMemo(()=>{const s=new Set([currentYear(),year,...(data?.years||[]),...(sales?.years||[])]);return[...s].sort((a,b)=>b-a)},[data,sales,year])
 return <div className="page field-dossier-page">
  <div className="page-head"><div><button className="back-link-button" onClick={()=>navigate('/fields')}><ArrowLeft size={16}/>圃場一覧</button><p className="eyebrow">FIELD DOSSIER</p><h1>{data?`${data.field.legacyId} ${data.field.name}`:'圃場カルテ'}</h1><p className="sub">許可された防除・施肥・摘採・製茶・販売情報を、圃場単位で一元表示します。</p></div><div className="head-actions">{canRecordHarvest&&<button className="secondary-button" onClick={()=>navigate(`/harvests?field=${fieldId||''}`)}><Scissors size={16}/>摘採・製茶を記録</button>}<select value={year} onChange={e=>setYear(Number(e.target.value))}>{years.map(y=><option key={y} value={y}>{y}年</option>)}</select><button className="icon-button" onClick={()=>void refresh()} disabled={loading}><RefreshCw size={18} className={loading?'spin':''}/></button></div></div>
  {error&&<div className="notice error dashboard-notice">{error}</div>}
  {data&&<>
   <section className="panel dossier-field-header"><div className="dossier-field-main"><div className="dossier-map-icon"><MapPinned size={24}/></div><div><b>{data.field.location||'場所未設定'}</b><span>{data.field.variety||'品種未設定'} / {data.field.cultivationType||'栽培区分未設定'}</span></div></div><div className="dossier-field-meta"><div><span>面積</span><b>{num.format(data.field.areaM2)}㎡</b><small>{(data.field.areaM2/1000).toFixed(4)}反</small></div><div><span>摘採予定</span><b>{data.field.harvestDate||'未登録'}</b></div><div><span>状態</span><b>{data.field.status==='active'?'有効':'休止'}</b></div></div>{data.field.note&&<p>{data.field.note}</p>}</section>
   <div className="dossier-metrics"><article><span>散布実績</span><strong>{data.summary.sprayCount}回</strong><small>{data.summary.pesticides.length?data.summary.pesticides.join(' / '):'使用農薬なし'}</small></article><article><span>施肥実績</span><strong>{data.summary.fertilizerCount}回</strong><small>{num.format(data.summary.fertilizerKg)}kg</small></article><article><span>N投入</span><strong>{num.format(data.summary.nKg)}kg</strong></article><article><span>P投入</span><strong>{num.format(data.summary.pKg)}kg</strong></article><article><span>K投入</span><strong>{num.format(data.summary.kKg)}kg</strong></article></div>
   <div className="dossier-metrics dossier-production-metrics"><article><span>摘採</span><strong>{data.summary.harvestCount}回</strong><small>生葉 {num.format(data.summary.freshLeafKg)}kg</small></article><article><span>生葉収量 / 10a</span><strong>{num.format(data.summary.yieldKgPer10a)}kg</strong></article><article><span>製茶</span><strong>{data.summary.processingCount}回</strong><small>投入 {num.format(data.summary.processedInputKg)}kg</small></article><article><span>圃場按分出来高</span><strong>{num.format(data.summary.processedOutputKg)}kg</strong></article><article><span>製茶歩留</span><strong>{data.summary.processingCount?`${data.summary.processingYieldPct.toFixed(2)}%`:'—'}</strong></article>{canViewSales&&<><article><span>販売</span><strong>{sales?sales.saleCount:0}件</strong><small>圃場由来商品の販売</small></article><article><span>圃場按分売上</span><strong>{sales?yen.format(sales.attributedSalesYen):'—'}</strong></article><article><span>圃場按分粗利</span><strong>{sales?yen.format(sales.attributedGrossProfitYen):'—'}</strong><small>{sales?`粗利率 ${sales.grossMarginPct.toFixed(1)}%`:''}</small></article></>}</div>
   <section className="panel dossier-timeline-panel"><div className="panel-title"><div><h2>{year}年 作業タイムライン</h2><p>権限のある栽培・摘採・製茶の実績と予定を同じ時系列で表示</p></div><span>{data.events.length}件</span></div><div className="dossier-timeline">{data.events.map(ev=><article className={`dossier-event ${ev.type}`} key={ev.id}><div className="dossier-event-rail"><span>{icon(ev.type)}</span></div><div className="dossier-event-body"><div className="dossier-event-top"><div><span className="dossier-event-type">{label(ev.type)}</span><b>{ev.date}</b></div>{ev.status&&<span className={`status-pill ${ev.status}`}>{ev.status==='completed'?'実施済':ev.status==='cancelled'?'中止':'予定'}</span>}</div><h3>{ev.title}</h3><p>{ev.subtitle}</p><small>{ev.detail}</small>{ev.type==='fertilizer'&&<div className="dossier-event-npk"><span>N {num.format(ev.n||0)}kg</span><span>P {num.format(ev.p||0)}kg</span><span>K {num.format(ev.k||0)}kg</span></div>}</div></article>)}{!loading&&!data.events.length&&<p className="empty">{year}年の表示可能な作業記録・予定はありません。</p>}</div></section>
   {canViewSales&&<section className="panel dossier-sales-panel"><div className="panel-title"><div><h2>{year}年 販売トレーサビリティ</h2><p>この圃場の摘採分が含まれる販売を、製品ロットから逆算して按分表示</p></div><ShoppingCart size={21}/></div><div className="dossier-sale-list">{(sales?.events||[]).map(s=>{const margin=s.attributedSalesYen>0?s.attributedGrossProfitYen/s.attributedSalesYen*100:0;return <article className="dossier-sale-card" key={s.saleId}><div className="dossier-sale-head"><div><span>{s.date} / {s.legacyId}</span><h3>{s.customerName}</h3><small>{s.channel||'—'}{s.invoiceNo?` ・ ${s.invoiceNo}`:''}</small></div><div><b>{yen.format(s.attributedSalesYen)}</b><span>按分粗利 {yen.format(s.attributedGrossProfitYen)} ({margin.toFixed(1)}%)</span></div></div><div className="dossier-sale-items">{s.items.map(i=><div key={`${s.saleId}-${i.salesItemId}`}><div><b>{i.materialName}</b><span>{i.lotLegacyId}</span></div><span>圃場由来 {(i.sourceShare*100).toFixed(1)}%</span><span>製品換算 {num.format(i.attributedQty)} {i.unit}</span><span>按分売上 {yen.format(i.attributedSalesYen)}</span></div>)}</div></article>})}{!loading&&!sales?.events.length&&<p className="empty">{year}年に、この圃場由来として追跡できる販売はありません。</p>}</div></section>}
  </>}
 </div>
}
