import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { Calculator, ClipboardCheck, Edit3, Factory, PackagePlus, RefreshCw, Search, Trash2, X } from 'lucide-react'
import { adjustProductionLot, deleteManufacturingBatch, disposeProductionLot, loadManufacturingBatches, loadProductionLots, loadProductionRole, loadProductionTransactions, receiveProductionLot, saveManufacturingBatch, type ManufacturingBatch, type ProductionLot, type ProductionTransaction } from '../lib/production'

const today=()=>new Intl.DateTimeFormat('sv-SE').format(new Date())
const num=new Intl.NumberFormat('ja-JP',{maximumFractionDigits:3})
const yen=new Intl.NumberFormat('ja-JP',{style:'currency',currency:'JPY',maximumFractionDigits:0})
type Tab='inventory'|'manufacturing'|'cost'
type Modal='receive'|'adjust'|'dispose'|null
const sourceLabel=(s:string)=>s==='PRIMARY_PROCESSING'?'一次製茶':s==='MANUFACTURING'?'加工':'外部入庫'

export default function ProductionPage(){
 const[tab,setTab]=useState<Tab>('inventory'),[lots,setLots]=useState<ProductionLot[]>([]),[batches,setBatches]=useState<ManufacturingBatch[]>([]),[tx,setTx]=useState<ProductionTransaction[]>([]),[role,setRole]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(''),[q,setQ]=useState('')
 const[modal,setModal]=useState<Modal>(null),[selectedLot,setSelectedLot]=useState<ProductionLot|null>(null),[physical,setPhysical]=useState(''),[disposeQty,setDisposeQty]=useState(''),[reason,setReason]=useState('')
 const[receive,setReceive]=useState({materialName:'',category:'原料',unit:'kg',receivedDate:today(),quantity:'',totalCostYen:'0',supplier:'',storageLocation:'製品保管庫',note:''})
 const[mId,setMId]=useState(''),[mDate,setMDate]=useState(today()),[processType,setProcessType]=useState(''),[outputMaterial,setOutputMaterial]=useState(''),[outputQty,setOutputQty]=useState(''),[outputUnit,setOutputUnit]=useState('kg'),[outputCategory,setOutputCategory]=useState('製品'),[facility,setFacility]=useState(''),[processingCost,setProcessingCost]=useState('0'),[packagingCost,setPackagingCost]=useState('0'),[otherCost,setOtherCost]=useState('0'),[operator,setOperator]=useState(''),[note,setNote]=useState(''),[inputs,setInputs]=useState<Record<string,string>>({})
 async function refresh(){setLoading(true);setError('');try{const[l,b,t,r]=await Promise.all([loadProductionLots(),loadManufacturingBatches(),loadProductionTransactions(),loadProductionRole()]);setLots(l);setBatches(b);setTx(t);setRole(r)}catch(e:any){setError(e?.message||'製造・製品データを読み込めませんでした。')}finally{setLoading(false)}}
 useEffect(()=>{void refresh()},[])
 const isAdmin=role==='admin'
 const activeLots=lots.filter(l=>l.balance>0.0005),inventoryValue=activeLots.reduce((s,l)=>s+l.inventoryValueYen,0)
 const filteredLots=useMemo(()=>{const x=q.trim().normalize('NFKC').toLowerCase();if(!x)return lots;return lots.filter(l=>`${l.legacyId} ${l.materialName} ${l.category} ${l.supplier} ${l.storageLocation}`.normalize('NFKC').toLowerCase().includes(x))},[lots,q])
 const currentBatch=batches.find(b=>b.id===mId),oldInput=new Map((currentBatch?.inputs||[]).map(i=>[i.lotId,i.inputQty]))
 const selectableLots=lots.filter(l=>l.id!==currentBatch?.outputLotId&&l.balance+(oldInput.get(l.id)||0)>0.0005)
 const inputRows=selectableLots.filter(l=>inputs[l.id]!==undefined).map(l=>({lot:l,qty:Number(inputs[l.id]||0),available:l.balance+(oldInput.get(l.id)||0)}))
 const inherited=inputRows.reduce((s,x)=>s+x.qty*x.lot.unitCostYen,0),direct=Number(processingCost||0)+Number(packagingCost||0)+Number(otherCost||0),previewTotal=inherited+direct,previewUnit=Number(outputQty||0)>0?previewTotal/Number(outputQty):0
 const sameUnit=inputRows.length>0&&inputRows.every(x=>x.lot.unit===outputUnit),inputTotal=sameUnit?inputRows.reduce((s,x)=>s+x.qty,0):0,yieldPct=sameUnit&&inputTotal>0&&Number(outputQty||0)>0?Number(outputQty)/inputTotal*100:0
 function resetManufacturing(){setMId('');setMDate(today());setProcessType('');setOutputMaterial('');setOutputQty('');setOutputUnit('kg');setOutputCategory('製品');setFacility('');setProcessingCost('0');setPackagingCost('0');setOtherCost('0');setOperator('');setNote('');setInputs({})}
 function editManufacturing(b:ManufacturingBatch){setTab('manufacturing');setMId(b.id);setMDate(b.date);setProcessType(b.processType);setOutputMaterial(b.outputMaterial);setOutputQty(String(b.outputQty));setOutputUnit(b.outputUnit);setOutputCategory(lots.find(l=>l.id===b.outputLotId)?.category||'製品');setFacility(b.facility);setProcessingCost(String(b.processingCostYen));setPackagingCost(String(b.packagingCostYen));setOtherCost(String(b.otherCostYen));setOperator(b.operator);setNote(b.note);setInputs(Object.fromEntries(b.inputs.map(i=>[i.lotId,String(i.inputQty)])));window.scrollTo({top:0,behavior:'smooth'})}
 function toggleInput(l:ProductionLot){setInputs(old=>{const next={...old};if(next[l.id]!==undefined)delete next[l.id];else next[l.id]=String((l.balance+(oldInput.get(l.id)||0)).toFixed(3));return next})}
 async function submitManufacturing(e:FormEvent){e.preventDefault();setBusy(true);setError('');setSuccess('');try{const rows=inputRows.filter(x=>x.qty>0);if(!rows.length)throw new Error('原料ロットを選択してください。');for(const x of rows)if(x.qty>x.available+0.0005)throw new Error(`${x.lot.legacyId} の在庫を超えています。`);await saveManufacturingBatch({id:mId||undefined,date:mDate,processType,outputMaterial,outputQty:Number(outputQty),outputUnit,category:outputCategory,facility,processingCostYen:Number(processingCost||0),packagingCostYen:Number(packagingCost||0),otherCostYen:Number(otherCost||0),operator,note,inputs:rows.map(x=>({lotId:x.lot.id,inputQty:x.qty}))});setSuccess(mId?'加工実績を更新しました。':'加工実績を登録し、出来高を新ロットへ入庫しました。');resetManufacturing();await refresh()}catch(e:any){setError(e?.message||'加工実績を保存できませんでした。')}finally{setBusy(false)}}
 async function removeManufacturing(b:ManufacturingBatch){const r=window.prompt('加工実績の削除理由を入力してください。原料は在庫へ戻ります。','入力誤り');if(r===null)return;setBusy(true);setError('');try{await deleteManufacturingBatch(b.id,r);setSuccess('加工実績を削除し、原料在庫へ戻入しました。');await refresh()}catch(e:any){setError(e?.message||'加工実績を削除できませんでした。')}finally{setBusy(false)}}
 function closeModal(){setModal(null);setSelectedLot(null);setPhysical('');setDisposeQty('');setReason('')}
 async function submitReceive(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{await receiveProductionLot({materialName:receive.materialName,category:receive.category,unit:receive.unit,receivedDate:receive.receivedDate,quantity:Number(receive.quantity),totalCostYen:Number(receive.totalCostYen||0),supplier:receive.supplier,storageLocation:receive.storageLocation,note:receive.note});setSuccess('原料・製品ロットを入庫しました。');setReceive({...receive,materialName:'',receivedDate:today(),quantity:'',totalCostYen:'0',supplier:'',note:''});closeModal();await refresh()}catch(e:any){setError(e?.message||'入庫できませんでした。')}finally{setBusy(false)}}
 async function submitAdjust(e:FormEvent){e.preventDefault();if(!selectedLot)return;setBusy(true);try{await adjustProductionLot(selectedLot.id,Number(physical),reason);setSuccess('棚卸調整を登録しました。');closeModal();await refresh()}catch(e:any){setError(e?.message||'棚卸できませんでした。')}finally{setBusy(false)}}
 async function submitDispose(e:FormEvent){e.preventDefault();if(!selectedLot)return;setBusy(true);try{await disposeProductionLot(selectedLot.id,Number(disposeQty),reason);setSuccess('廃棄を登録しました。');closeModal();await refresh()}catch(e:any){setError(e?.message||'廃棄できませんでした。')}finally{setBusy(false)}}
 return <div className="page production-page">
  <div className="page-head"><div><p className="eyebrow">PRODUCTION & COSTING</p><h1>製造・製品在庫</h1><p className="sub">製茶出来高から二次加工・製品在庫・ロット原価まで一続きで管理します。</p></div><div className="head-actions">{isAdmin&&<button className="secondary-button" onClick={()=>setModal('receive')}><PackagePlus size={17}/>原料・製品を入庫</button>}<button className="icon-button" onClick={()=>void refresh()} disabled={loading}><RefreshCw size={18} className={loading?'spin':''}/></button></div></div>
  {error&&<div className="notice error dashboard-notice">{error}</div>}{success&&<div className="notice success dashboard-notice">{success}</div>}
  <div className="metrics production-metrics"><article className="metric"><span>現在庫評価額</span><strong>{yen.format(inventoryValue)}</strong></article><article className="metric"><span>在庫ありロット</span><strong>{activeLots.length}件</strong></article><article className="metric"><span>製品ロット</span><strong>{activeLots.filter(l=>l.category==='製品').length}件</strong></article><article className="metric"><span>二次加工実績</span><strong>{batches.length}件</strong></article></div>
  <div className="production-tabs"><button className={tab==='inventory'?'active':''} onClick={()=>setTab('inventory')}>在庫</button><button className={tab==='manufacturing'?'active':''} onClick={()=>setTab('manufacturing')}>加工</button><button className={tab==='cost'?'active':''} onClick={()=>setTab('cost')}>原価</button></div>

  {tab==='inventory'&&<>
   <section className="panel"><div className="toolbar"><div className="search-box"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="品目・ロット・仕入先・保管場所を検索"/></div><span className="muted">{filteredLots.length}件</span></div><div className="production-lot-grid">{filteredLots.map(l=><article className={`production-lot-card ${l.balance<=0?'zero':''}`} key={l.id}><div className="production-lot-head"><div><span>{l.legacyId}</span><h3>{l.materialName}</h3></div><b>{l.category}</b></div><strong className="production-balance">{num.format(l.balance)} {l.unit}</strong><dl><div><dt>由来</dt><dd>{sourceLabel(l.sourceType)}</dd></div><div><dt>入庫日</dt><dd>{l.receivedDate||'—'}</dd></div><div><dt>単位原価</dt><dd>{yen.format(l.unitCostYen)} / {l.unit}</dd></div><div><dt>現在庫評価</dt><dd>{yen.format(l.inventoryValueYen)}</dd></div><div><dt>仕入・加工先</dt><dd>{l.supplier||'—'}</dd></div><div><dt>保管</dt><dd>{l.storageLocation||'—'}</dd></div></dl>{l.note&&<p>{l.note}</p>}{isAdmin&&<div className="production-card-actions"><button onClick={()=>{setSelectedLot(l);setPhysical(String(l.balance));setReason('');setModal('adjust')}}><ClipboardCheck size={14}/>棚卸</button><button disabled={l.balance<=0} className="danger-text-button" onClick={()=>{setSelectedLot(l);setDisposeQty('');setReason('');setModal('dispose')}}><Trash2 size={14}/>廃棄</button></div>}</article>)}{!loading&&!filteredLots.length&&<p className="empty">原料・製品在庫はまだありません。</p>}</div></section>
   <section className="panel"><div className="panel-title"><div><h2>在庫履歴</h2><p>入庫・加工使用・戻入・棚卸・廃棄</p></div><span>{tx.length}件</span></div><div className="production-tx-list">{tx.slice(0,100).map(t=><div key={t.id}><span>{new Date(t.createdAt).toLocaleString('ja-JP')}</span><b>{t.lotLegacyId} {t.materialName}</b><strong className={t.quantity>=0?'plus':'minus'}>{t.quantity>=0?'+':''}{num.format(t.quantity)} {t.unit}</strong><small>{t.reason||t.type}</small></div>)}{!tx.length&&<p className="empty">在庫履歴はありません。</p>}</div></section>
  </>}

  {tab==='manufacturing'&&<>
   <form className="panel manufacturing-form" onSubmit={submitManufacturing}><div className="panel-title"><div><h2>{mId?'加工実績を編集':'二次加工を記録'}</h2><p>碾茶→抹茶、ブレンド、袋詰め・缶詰めまでロットでつなぎます。</p></div>{mId&&<button type="button" className="secondary-button" onClick={resetManufacturing}>新規へ戻る</button>}</div>
    <div className="form-grid four"><label>加工日<input type="date" value={mDate} onChange={e=>setMDate(e.target.value)}/></label><label>加工工程<input list="mfg-process" value={processType} onChange={e=>setProcessType(e.target.value)} required placeholder="碾茶→抹茶"/><datalist id="mfg-process"><option value="碾茶→抹茶"/><option value="碾茶ブレンド"/><option value="抹茶→缶詰め"/><option value="玉露→袋詰め"/><option value="ほうじ茶→袋詰め"/></datalist></label><label>出来上がり品目<input value={outputMaterial} onChange={e=>setOutputMaterial(e.target.value)} required placeholder="抹茶 やぶきた"/></label><label>区分<select value={outputCategory} onChange={e=>setOutputCategory(e.target.value)}><option>原料</option><option>製品</option></select></label><label>出来高<input type="number" min="0.001" step="0.001" value={outputQty} onChange={e=>setOutputQty(e.target.value)} required/></label><label>出来高単位<select value={outputUnit} onChange={e=>setOutputUnit(e.target.value)}><option>kg</option><option>g</option><option>缶</option><option>袋</option><option>箱</option><option>個</option></select></label><label>加工先・設備<input value={facility} onChange={e=>setFacility(e.target.value)}/></label><label>担当者<input value={operator} onChange={e=>setOperator(e.target.value)}/></label></div>
    <div className="manufacturing-cost-grid"><label>加工費（円）<input type="number" min="0" step="1" value={processingCost} onChange={e=>setProcessingCost(e.target.value)}/></label><label>包装資材費（円）<input type="number" min="0" step="1" value={packagingCost} onChange={e=>setPackagingCost(e.target.value)}/></label><label>その他直接費（円）<input type="number" min="0" step="1" value={otherCost} onChange={e=>setOtherCost(e.target.value)}/></label></div>
    <div className="production-input-section"><div className="section-head"><div><h3>原料ロット</h3><p className="muted">在庫のあるロットから選択。複数ロットのブレンドにも対応。</p></div></div><div className="production-input-lots">{selectableLots.map(l=>{const checked=inputs[l.id]!==undefined,available=l.balance+(oldInput.get(l.id)||0);return <article className={checked?'selected':''} key={l.id}><label><input type="checkbox" checked={checked} onChange={()=>toggleInput(l)}/><span><b>{l.materialName}</b><small>{l.legacyId}｜在庫 {num.format(available)} {l.unit}｜{yen.format(l.unitCostYen)}/{l.unit}</small></span></label>{checked&&<input className="production-input-qty" type="number" min="0.001" max={available} step="0.001" value={inputs[l.id]} onChange={e=>setInputs({...inputs,[l.id]:e.target.value})}/>}</article>})}{!selectableLots.length&&<p className="empty">加工に使える在庫ロットがありません。</p>}</div></div>
    <div className="manufacturing-preview"><div><span>持越原価</span><b>{yen.format(inherited)}</b></div><div><span>今回直接費</span><b>{yen.format(direct)}</b></div><div><span>総製造原価</span><b>{yen.format(previewTotal)}</b></div><div><span>出来高単位原価</span><b>{previewUnit?`${yen.format(previewUnit)} / ${outputUnit}`:'—'}</b></div><div><span>歩留</span><b>{yieldPct?`${yieldPct.toFixed(2)}%`:'単位が異なるため算出なし'}</b></div></div>
    <label>備考<textarea rows={2} value={note} onChange={e=>setNote(e.target.value)}/></label><button className="primary-button manufacturing-save" disabled={busy}>{busy?'保存中…':mId?'変更を保存':'加工を登録'}</button>
   </form>
   <section className="panel"><div className="panel-title"><div><h2>加工履歴</h2><p>原料ロット→出来高ロットの系譜と原価を保持</p></div><span>{batches.length}件</span></div><div className="manufacturing-history">{batches.map(b=><article key={b.id}><div className="manufacturing-history-head"><div><span>{b.date}</span><h3>{b.processType}</h3><small>{b.legacyId} / {b.facility||'加工先未入力'}</small></div><div><strong>{num.format(b.outputQty)} {b.outputUnit}</strong><b>{b.outputMaterial}</b></div></div><div className="manufacturing-lineage">{b.inputs.map(i=><span key={i.id}>{i.lotLegacyId} {i.materialName}：{num.format(i.inputQty)} {i.unit}（{yen.format(i.inputCostYen)}）</span>)}</div><div className="manufacturing-history-cost"><span>持越 {yen.format(b.inheritedInputCostYen)}</span><span>加工 {yen.format(b.processingCostYen)}</span><span>包装 {yen.format(b.packagingCostYen)}</span><span>その他 {yen.format(b.otherCostYen)}</span><b>総原価 {yen.format(b.totalCostYen)}</b></div><div className="production-card-actions"><button onClick={()=>editManufacturing(b)}><Edit3 size={14}/>編集</button>{isAdmin&&<button className="danger-text-button" disabled={busy} onClick={()=>void removeManufacturing(b)}><Trash2 size={14}/>削除</button>}</div></article>)}{!loading&&!batches.length&&<p className="empty">二次加工実績はまだありません。</p>}</div></section>
  </>}

  {tab==='cost'&&<section className="panel"><div className="panel-title"><div><h2>ロット原価一覧</h2><p>前工程原価を持ち越した登録済み製造原価。栽培人件費等はまだ含みません。</p></div><Calculator size={20}/></div><div className="production-cost-table"><div className="production-cost-head"><span>ロット / 品目</span><span>区分</span><span>当初数量</span><span>現在庫</span><span>総原価</span><span>単位原価</span><span>現在庫評価</span></div>{lots.map(l=><div className="production-cost-row" key={l.id}><div><b>{l.materialName}</b><small>{l.legacyId}｜{sourceLabel(l.sourceType)}</small></div><span>{l.category}</span><span>{num.format(l.initialQty)} {l.unit}</span><span>{num.format(l.balance)} {l.unit}</span><span>{yen.format(l.totalCostYen)}</span><strong>{yen.format(l.unitCostYen)} / {l.unit}</strong><b>{yen.format(l.inventoryValueYen)}</b></div>)}{!lots.length&&<p className="empty">原価対象ロットはまだありません。</p>}</div></section>}

  {modal&&<div className="inventory-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)closeModal()}}><section className="panel inventory-modal production-modal"><div className="section-head"><div><p className="eyebrow">{modal==='receive'?'RECEIVING':modal==='adjust'?'STOCKTAKE':'DISPOSAL'}</p><h2>{modal==='receive'?'原料・製品を入庫':modal==='adjust'?'在庫を棚卸':'在庫を廃棄'}</h2></div><button className="close-detail" onClick={closeModal}><X size={17}/></button></div>
   {modal==='receive'&&<form className="inventory-action-form" onSubmit={submitReceive}><div className="form-grid two"><label>品目名<input required value={receive.materialName} onChange={e=>setReceive({...receive,materialName:e.target.value})} placeholder="購入碾茶 / 抹茶など"/></label><label>区分<select value={receive.category} onChange={e=>setReceive({...receive,category:e.target.value})}><option>原料</option><option>製品</option></select></label></div><div className="form-grid three"><label>入庫日<input type="date" value={receive.receivedDate} onChange={e=>setReceive({...receive,receivedDate:e.target.value})}/></label><label>数量<input required type="number" min="0.001" step="0.001" value={receive.quantity} onChange={e=>setReceive({...receive,quantity:e.target.value})}/></label><label>単位<select value={receive.unit} onChange={e=>setReceive({...receive,unit:e.target.value})}><option>kg</option><option>g</option><option>缶</option><option>袋</option><option>箱</option><option>個</option></select></label></div><label>取得総原価（円）<input type="number" min="0" step="1" value={receive.totalCostYen} onChange={e=>setReceive({...receive,totalCostYen:e.target.value})}/></label><div className="inventory-calc-note">単位原価：<b>{Number(receive.quantity||0)>0?`${yen.format(Number(receive.totalCostYen||0)/Number(receive.quantity))} / ${receive.unit}`:'—'}</b></div><div className="form-grid two"><label>購入先<input value={receive.supplier} onChange={e=>setReceive({...receive,supplier:e.target.value})}/></label><label>保管場所<input value={receive.storageLocation} onChange={e=>setReceive({...receive,storageLocation:e.target.value})}/></label></div><label>備考<textarea rows={2} value={receive.note} onChange={e=>setReceive({...receive,note:e.target.value})}/></label><button className="primary-button" disabled={busy}>{busy?'登録中…':'入庫を登録'}</button></form>}
   {modal==='adjust'&&selectedLot&&<form className="inventory-action-form" onSubmit={submitAdjust}><p><b>{selectedLot.materialName}</b>　現在 {num.format(selectedLot.balance)} {selectedLot.unit}</p><label>実在庫（{selectedLot.unit}）<input required type="number" min="0" step="0.001" value={physical} onChange={e=>setPhysical(e.target.value)}/></label><label>棚卸理由<input required value={reason} onChange={e=>setReason(e.target.value)}/></label><button className="primary-button" disabled={busy}>棚卸を登録</button></form>}
   {modal==='dispose'&&selectedLot&&<form className="inventory-action-form" onSubmit={submitDispose}><p><b>{selectedLot.materialName}</b>　現在 {num.format(selectedLot.balance)} {selectedLot.unit}</p><label>廃棄量（{selectedLot.unit}）<input required type="number" min="0.001" max={selectedLot.balance} step="0.001" value={disposeQty} onChange={e=>setDisposeQty(e.target.value)}/></label><label>廃棄理由<input required value={reason} onChange={e=>setReason(e.target.value)}/></label><button className="primary-button danger-button" disabled={busy}>廃棄を登録</button></form>}
  </section></div>}
 </div>
}
