import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { ChevronDown, ChevronUp, Download, RefreshCw, RotateCcw, ShoppingCart, Truck } from 'lucide-react'
import { cancelSale, loadSaleableLots, loadSales, registerSale, type SaleBundle } from '../lib/sales'
import type { ProductionLot } from '../lib/production'
import { useAppPermissions } from '../lib/permissions'

const today=()=>new Intl.DateTimeFormat('sv-SE').format(new Date())
const yen=new Intl.NumberFormat('ja-JP',{style:'currency',currency:'JPY',maximumFractionDigits:0})
const num=new Intl.NumberFormat('ja-JP',{maximumFractionDigits:3})

type Line={qty:string;price:string}
export default function SalesPage(){
 const { allowed }=useAppPermissions();const canManage=allowed('sales.manage')
 const[lots,setLots]=useState<ProductionLot[]>([]),[sales,setSales]=useState<SaleBundle[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(''),[q,setQ]=useState(''),[expanded,setExpanded]=useState('')
 const[date,setDate]=useState(today()),[customer,setCustomer]=useState(''),[channel,setChannel]=useState('卸'),[invoice,setInvoice]=useState(''),[destination,setDestination]=useState(''),[note,setNote]=useState(''),[lines,setLines]=useState<Record<string,Line>>({})
 async function refresh(){setLoading(true);setError('');try{const[l,s]=await Promise.all([loadSaleableLots(),loadSales()]);setLots(l);setSales(s)}catch(e:any){setError(e?.message||'販売データを読み込めませんでした。')}finally{setLoading(false)}}
 useEffect(()=>{void refresh()},[])
 useEffect(()=>{if(!canManage)setLines({})},[canManage])
 const selected=lots.filter(l=>lines[l.id]!==undefined).map(l=>({lot:l,qty:Number(lines[l.id]?.qty||0),price:Number(lines[l.id]?.price||0)}))
 const previewSales=selected.reduce((s,x)=>s+x.qty*x.price,0),previewCost=selected.reduce((s,x)=>s+x.qty*x.lot.unitCostYen,0),previewProfit=previewSales-previewCost
 const active=sales.filter(x=>x.summary.status==='ACTIVE'),month=today().slice(0,7),monthly=active.filter(x=>x.summary.date.startsWith(month)),monthSales=monthly.reduce((s,x)=>s+x.summary.salesAmountYen,0),monthCost=monthly.reduce((s,x)=>s+x.summary.costAmountYen,0),monthProfit=monthSales-monthCost
 const filtered=useMemo(()=>{const x=q.trim().normalize('NFKC').toLowerCase();if(!x)return sales;return sales.filter(s=>`${s.summary.legacyId} ${s.summary.customerName} ${s.summary.channel} ${s.summary.invoiceNo} ${s.items.map(i=>`${i.materialName} ${i.lotLegacyId}`).join(' ')}`.normalize('NFKC').toLowerCase().includes(x))},[sales,q])
 function toggle(l:ProductionLot){if(!canManage)return;setLines(old=>{const n={...old};if(n[l.id]!==undefined)delete n[l.id];else n[l.id]={qty:'',price:''};return n})}
 async function submit(e:FormEvent){e.preventDefault();if(!canManage)return setError('販売・出庫を登録する権限がありません。');setBusy(true);setError('');setSuccess('');try{const items=selected.filter(x=>x.qty>0).map(x=>({lotId:x.lot.id,quantity:x.qty,unitPriceYen:x.price}));if(!items.length)throw new Error('販売するロットと数量を入力してください。');for(const x of selected)if(x.qty>x.lot.balance+0.0005)throw new Error(`${x.lot.legacyId} の在庫を超えています。`);await registerSale({date,customerName:customer,channel,invoiceNo:invoice,destination,note,items});setSuccess('販売を登録し、製品在庫から出庫しました。');setCustomer('');setInvoice('');setDestination('');setNote('');setLines({});await refresh()}catch(e:any){setError(e?.message||'販売を登録できませんでした。')}finally{setBusy(false)}}
 async function cancel(s:SaleBundle){if(!canManage)return setError('販売を取り消す権限がありません。');const reason=window.prompt('取消理由を入力してください。販売数量は元ロットへ戻ります。','入力誤り');if(reason===null)return;setBusy(true);setError('');try{await cancelSale(s.summary.id,reason);setSuccess('販売を取り消し、在庫へ戻入しました。');await refresh()}catch(e:any){setError(e?.message||'販売を取り消せませんでした。')}finally{setBusy(false)}}
 function csv(){const rows=[['販売日','販売ID','販売先','チャネル','伝票番号','品目','ロット','数量','単位','販売単価','売上','原価','粗利','状態']];for(const s of filtered)for(const i of s.items)rows.push([s.summary.date,s.summary.legacyId,s.summary.customerName,s.summary.channel,s.summary.invoiceNo,i.materialName,i.lotLegacyId,String(i.quantity),i.unit,String(i.unitPriceYen),String(i.salesAmountYen),String(i.costAmountYen),String(i.grossProfitYen),s.summary.status]);const text='\uFEFF'+rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'}));a.download=`sales-${today()}.csv`;a.click();URL.revokeObjectURL(a.href)}
 return <div className="page sales-page">
  <div className="page-head"><div><p className="eyebrow">SALES & TRACEABILITY</p><h1>販売・出庫</h1><p className="sub">製品ロットから販売先までつなぎ、売上・原価・粗利と圃場由来を追跡します。</p></div><button className="icon-button" onClick={()=>void refresh()} disabled={loading}><RefreshCw size={18} className={loading?'spin':''}/></button></div>
  {error&&<div className="notice error dashboard-notice">{error}</div>}{success&&<div className="notice success dashboard-notice">{success}</div>}
  <div className="metrics sales-metrics"><article className="metric"><span>今月売上</span><strong>{yen.format(monthSales)}</strong></article><article className="metric"><span>今月売上原価</span><strong>{yen.format(monthCost)}</strong></article><article className="metric"><span>今月粗利</span><strong>{yen.format(monthProfit)}</strong></article><article className="metric"><span>粗利率</span><strong>{monthSales>0?(monthProfit/monthSales*100).toFixed(1):'0.0'}%</strong></article></div>
  {canManage&&<form className="panel sales-entry" onSubmit={submit}><div className="panel-title"><div><h2>販売を登録</h2><p>販売すると選択ロットから即時出庫します。</p></div><ShoppingCart size={22}/></div><div className="form-grid four"><label>販売日<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>販売先<input value={customer} onChange={e=>setCustomer(e.target.value)} required placeholder="例：○○商店"/></label><label>チャネル<input list="sales-channel" value={channel} onChange={e=>setChannel(e.target.value)}/><datalist id="sales-channel"><option value="卸"/><option value="小売"/><option value="EC"/><option value="イベント"/><option value="サンプル"/></datalist></label><label>伝票・注文番号<input value={invoice} onChange={e=>setInvoice(e.target.value)}/></label><label className="span-2">発送先<input value={destination} onChange={e=>setDestination(e.target.value)}/></label><label className="span-2">備考<input value={note} onChange={e=>setNote(e.target.value)}/></label></div>
   <div className="sale-lot-picker">{lots.map(l=><label className={lines[l.id]!==undefined?'selected':''} key={l.id}><input type="checkbox" checked={lines[l.id]!==undefined} onChange={()=>toggle(l)}/><div><b>{l.materialName}</b><span>{l.legacyId} / 在庫 {num.format(l.balance)} {l.unit} / 原価 {yen.format(l.unitCostYen)}/{l.unit}</span></div>{lines[l.id]!==undefined&&<div className="sale-line-inputs" onClick={e=>e.preventDefault()}><input type="number" min="0.001" step="0.001" placeholder="数量" value={lines[l.id].qty} onChange={e=>setLines(x=>({...x,[l.id]:{...x[l.id],qty:e.target.value}}))}/><input type="number" min="0" step="1" placeholder={`単価/${l.unit}`} value={lines[l.id].price} onChange={e=>setLines(x=>({...x,[l.id]:{...x[l.id],price:e.target.value}}))}/></div>}</label>)}{!lots.length&&<p className="empty">販売可能な原料・製品在庫がありません。</p>}</div>
   <div className="sales-preview"><div><span>売上</span><strong>{yen.format(previewSales)}</strong></div><div><span>原価</span><strong>{yen.format(previewCost)}</strong></div><div><span>粗利</span><strong>{yen.format(previewProfit)}</strong></div><div><span>粗利率</span><strong>{previewSales>0?(previewProfit/previewSales*100).toFixed(1):'0.0'}%</strong></div></div><button className="primary-button" disabled={busy||!selected.length}><Truck size={18}/>{busy?'登録中…':'販売・出庫を登録'}</button>
  </form>}
  <section className="panel"><div className="panel-title"><div><h2>販売履歴</h2><p>ロット原価・粗利・圃場トレーサビリティ</p></div><button className="secondary-button" type="button" onClick={csv}><Download size={16}/>CSV</button></div><div className="toolbar"><div className="search-box"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="販売先・品目・ロット・伝票番号を検索"/></div><span className="muted">{filtered.length}件</span></div><div className="sales-history">{filtered.map(s=>{const open=expanded===s.summary.id;const gp=s.summary.salesAmountYen>0?s.summary.grossProfitYen/s.summary.salesAmountYen*100:0;return <article className={`sale-card ${s.summary.status==='CANCELLED'?'cancelled':''}`} key={s.summary.id}><button className="sale-card-head" type="button" onClick={()=>setExpanded(open?'':s.summary.id)}><div><span>{s.summary.date} / {s.summary.legacyId}</span><h3>{s.summary.customerName}</h3><small>{s.summary.channel||'—'} {s.summary.invoiceNo&&`・${s.summary.invoiceNo}`}</small></div><div className="sale-card-totals"><b>{yen.format(s.summary.salesAmountYen)}</b><span>粗利 {yen.format(s.summary.grossProfitYen)} ({gp.toFixed(1)}%)</span></div>{open?<ChevronUp size={19}/>:<ChevronDown size={19}/>}</button>{open&&<div className="sale-detail"><div className="sale-items">{s.items.map(i=><div key={i.id}><div><b>{i.materialName}</b><span>{i.lotLegacyId}</span></div><span>{num.format(i.quantity)} {i.unit} × {yen.format(i.unitPriceYen)}</span><span>売上 {yen.format(i.salesAmountYen)}</span><span>原価 {yen.format(i.costAmountYen)}</span><strong>粗利 {yen.format(i.grossProfitYen)}</strong></div>)}</div>{s.traces.length>0&&<div className="sale-trace"><h4>圃場トレーサビリティ</h4>{s.traces.map((t,k)=><span key={`${t.salesItemId}-${t.fieldId}-${k}`}>{t.fieldLegacyId}｜{t.fieldName}：由来 {(t.sourceShare*100).toFixed(1)}%（製品換算 {num.format(t.attributedQty)} {t.unit}）</span>)}</div>}{s.summary.destination&&<p>発送先：{s.summary.destination}</p>}{s.summary.note&&<p>備考：{s.summary.note}</p>}{s.summary.status==='CANCELLED'?<div className="notice">取消済み：{s.summary.cancelReason}</div>:canManage&&<button className="danger-button" type="button" disabled={busy} onClick={()=>void cancel(s)}><RotateCcw size={16}/>販売を取消・在庫へ戻す</button>}</div>}</article>})}{!loading&&!filtered.length&&<p className="empty">販売履歴はまだありません。</p>}</div></section>
 </div>
}
