-- Official MAFF fertilizer registry snapshot and import linkage.
-- Applied to production on 2026-08-26.

create table if not exists public.fertilizer_official_registrations (
  id uuid primary key default gen_random_uuid(), source_key text not null unique, registration_no text, registration_category text,
  fertilizer_name text not null, company_name text, fertilizer_type text, registration_date date, expiration_date date, valid_period text, address text,
  tn numeric(10,4), an numeric(10,4), nn numeric(10,4), tp numeric(10,4), cp numeric(10,4), sp numeric(10,4), wp numeric(10,4),
  tk numeric(10,4), ck numeric(10,4), wk numeric(10,4), smg numeric(10,4), cmg numeric(10,4), wmg numeric(10,4), sca numeric(10,4), cca numeric(10,4), wca numeric(10,4),
  components jsonb not null default '{}'::jsonb, search_text text not null default '', source_date date not null,
  source_url text not null default 'https://fertilizer-search.maff.go.jp/FertilizerRegistrationSearch', sync_token uuid not null, synced_at timestamptz not null default now()
);
create index if not exists idx_fertilizer_official_name on public.fertilizer_official_registrations(fertilizer_name);
create index if not exists idx_fertilizer_official_registration on public.fertilizer_official_registrations(registration_no);
create index if not exists idx_fertilizer_official_type on public.fertilizer_official_registrations(fertilizer_type);
create index if not exists idx_fertilizer_official_expiry on public.fertilizer_official_registrations(expiration_date);

create table if not exists public.fertilizer_official_sync_log(id bigint generated always as identity primary key,source_date date not null,row_count integer not null,sync_token uuid not null,synced_by uuid references auth.users(id),completed_at timestamptz not null default now());
alter table public.fertilizer_official_registrations enable row level security; alter table public.fertilizer_official_sync_log enable row level security;
drop policy if exists fertilizer_official_read on public.fertilizer_official_registrations; create policy fertilizer_official_read on public.fertilizer_official_registrations for select to authenticated using(true);
drop policy if exists fertilizer_official_sync_log_read on public.fertilizer_official_sync_log; create policy fertilizer_official_sync_log_read on public.fertilizer_official_sync_log for select to authenticated using(true);
grant select on public.fertilizer_official_registrations,public.fertilizer_official_sync_log to authenticated;

alter table public.fertilizers add column if not exists official_registration_id uuid references public.fertilizer_official_registrations(id) on delete set null;
alter table public.fertilizers add column if not exists official_registration_no text;
alter table public.fertilizers add column if not exists official_source_date date;
create unique index if not exists uq_fertilizers_official_active on public.fertilizers(official_registration_id) where deleted_at is null and official_registration_id is not null;

create or replace function public.sync_official_fertilizer_chunk(p_rows jsonb,p_sync_token uuid,p_source_date date) returns integer language plpgsql security definer set search_path=public as $$
declare r jsonb;v_count integer:=0;v_key text;v_name text;
begin perform public.require_fertilizer_admin_(); if jsonb_typeof(p_rows)<>'array' then raise exception '同期データ形式が不正です'; end if;
for r in select * from jsonb_array_elements(p_rows) loop v_key:=btrim(coalesce(r->>'source_key',''));v_name:=btrim(coalesce(r->>'fertilizer_name',''));if v_key='' or v_name='' then continue;end if;
insert into public.fertilizer_official_registrations(source_key,registration_no,registration_category,fertilizer_name,company_name,fertilizer_type,registration_date,expiration_date,valid_period,address,tn,an,nn,tp,cp,sp,wp,tk,ck,wk,smg,cmg,wmg,sca,cca,wca,components,search_text,source_date,source_url,sync_token,synced_at)
values(v_key,nullif(btrim(r->>'registration_no'),''),nullif(btrim(r->>'registration_category'),''),v_name,nullif(btrim(r->>'company_name'),''),nullif(btrim(r->>'fertilizer_type'),''),nullif(r->>'registration_date','')::date,nullif(r->>'expiration_date','')::date,nullif(btrim(r->>'valid_period'),''),nullif(btrim(r->>'address'),''),nullif(r->>'tn','')::numeric,nullif(r->>'an','')::numeric,nullif(r->>'nn','')::numeric,nullif(r->>'tp','')::numeric,nullif(r->>'cp','')::numeric,nullif(r->>'sp','')::numeric,nullif(r->>'wp','')::numeric,nullif(r->>'tk','')::numeric,nullif(r->>'ck','')::numeric,nullif(r->>'wk','')::numeric,nullif(r->>'smg','')::numeric,nullif(r->>'cmg','')::numeric,nullif(r->>'wmg','')::numeric,nullif(r->>'sca','')::numeric,nullif(r->>'cca','')::numeric,nullif(r->>'wca','')::numeric,coalesce(r->'components','{}'::jsonb),coalesce(r->>'search_text',''),p_source_date,coalesce(nullif(r->>'source_url',''),'https://fertilizer-search.maff.go.jp/FertilizerRegistrationSearch'),p_sync_token,now())
on conflict(source_key) do update set registration_no=excluded.registration_no,registration_category=excluded.registration_category,fertilizer_name=excluded.fertilizer_name,company_name=excluded.company_name,fertilizer_type=excluded.fertilizer_type,registration_date=excluded.registration_date,expiration_date=excluded.expiration_date,valid_period=excluded.valid_period,address=excluded.address,tn=excluded.tn,an=excluded.an,nn=excluded.nn,tp=excluded.tp,cp=excluded.cp,sp=excluded.sp,wp=excluded.wp,tk=excluded.tk,ck=excluded.ck,wk=excluded.wk,smg=excluded.smg,cmg=excluded.cmg,wmg=excluded.wmg,sca=excluded.sca,cca=excluded.cca,wca=excluded.wca,components=excluded.components,search_text=excluded.search_text,source_date=excluded.source_date,source_url=excluded.source_url,sync_token=excluded.sync_token,synced_at=now();v_count:=v_count+1;end loop;return v_count;end $$;
revoke all on function public.sync_official_fertilizer_chunk(jsonb,uuid,date) from public,anon;grant execute on function public.sync_official_fertilizer_chunk(jsonb,uuid,date) to authenticated;

create or replace function public.finalize_official_fertilizer_sync(p_sync_token uuid,p_source_date date,p_row_count integer) returns integer language plpgsql security definer set search_path=public as $$
declare v_deleted integer;v_total integer;begin perform public.require_fertilizer_admin_();delete from public.fertilizer_official_registrations where sync_token<>p_sync_token;get diagnostics v_deleted=row_count;select count(*) into v_total from public.fertilizer_official_registrations where sync_token=p_sync_token;if v_total<>p_row_count then raise exception '同期件数が一致しません（DB %, 受信 %）',v_total,p_row_count;end if;insert into public.fertilizer_official_sync_log(source_date,row_count,sync_token,synced_by) values(p_source_date,v_total,p_sync_token,auth.uid());insert into public.audit_logs(user_id,action,entity_type,entity_id,after_data) values(auth.uid(),'SYNC','fertilizer_official_registry',p_sync_token::text,jsonb_build_object('source_date',p_source_date,'row_count',v_total,'deleted_old',v_deleted));return v_total;end $$;
revoke all on function public.finalize_official_fertilizer_sync(uuid,date,integer) from public,anon;grant execute on function public.finalize_official_fertilizer_sync(uuid,date,integer) to authenticated;

create or replace function public.search_official_fertilizers(p_query text default '',p_limit integer default 100,p_offset integer default 0) returns setof public.fertilizer_official_registrations language sql stable set search_path=public as $$ select r.* from public.fertilizer_official_registrations r where btrim(coalesce(p_query,''))='' or r.search_text ilike '%'||btrim(p_query)||'%' or coalesce(r.registration_no,'') ilike '%'||btrim(p_query)||'%' order by r.fertilizer_name,r.registration_no nulls last limit least(greatest(coalesce(p_limit,100),1),200) offset greatest(coalesce(p_offset,0),0) $$;
grant execute on function public.search_official_fertilizers(text,integer,integer) to authenticated;

create or replace function public.admin_save_fertilizer(p_payload jsonb) returns uuid language plpgsql security definer set search_path=public as $$
declare v_id uuid;v_before jsonb;v_after jsonb;v_name text;v_official uuid;v_reg text;v_source date;
begin perform public.require_fertilizer_admin_();v_id:=nullif(p_payload->>'id','')::uuid;v_name:=btrim(coalesce(p_payload->>'name',''));v_official:=nullif(p_payload->>'official_registration_id','')::uuid;if v_name='' then raise exception '肥料名を入力してください';end if;if v_official is not null then select registration_no,source_date into v_reg,v_source from public.fertilizer_official_registrations where id=v_official;if not found then raise exception '公式肥料データが見つかりません';end if;end if;
if v_id is null then insert into public.fertilizers(legacy_id,name,manufacturer,category,nitrogen_percent,phosphate_percent,potassium_percent,magnesium_percent,calcium_percent,note,is_active,official_registration_id,official_registration_no,official_source_date) values('FER-'||to_char(clock_timestamp(),'YYYYMMDDHH24MISS')||'-'||upper(substr(md5(random()::text),1,4)),v_name,nullif(btrim(p_payload->>'manufacturer'),''),nullif(btrim(p_payload->>'category'),''),coalesce(nullif(p_payload->>'nitrogen_percent','')::numeric,0),coalesce(nullif(p_payload->>'phosphate_percent','')::numeric,0),coalesce(nullif(p_payload->>'potassium_percent','')::numeric,0),coalesce(nullif(p_payload->>'magnesium_percent','')::numeric,0),coalesce(nullif(p_payload->>'calcium_percent','')::numeric,0),nullif(btrim(p_payload->>'note'),''),coalesce((p_payload->>'is_active')::boolean,true),v_official,v_reg,v_source) returning id into v_id;select to_jsonb(f) into v_after from public.fertilizers f where f.id=v_id;insert into public.audit_logs(user_id,action,entity_type,entity_id,after_data) values(auth.uid(),'CREATE','fertilizer',v_id::text,v_after);
else select to_jsonb(f) into v_before from public.fertilizers f where f.id=v_id for update;if v_before is null then raise exception '肥料が見つかりません';end if;if v_official is null then select official_registration_id,official_registration_no,official_source_date into v_official,v_reg,v_source from public.fertilizers where id=v_id;end if;update public.fertilizers set name=v_name,manufacturer=nullif(btrim(p_payload->>'manufacturer'),''),category=nullif(btrim(p_payload->>'category'),''),nitrogen_percent=coalesce(nullif(p_payload->>'nitrogen_percent','')::numeric,nitrogen_percent),phosphate_percent=coalesce(nullif(p_payload->>'phosphate_percent','')::numeric,phosphate_percent),potassium_percent=coalesce(nullif(p_payload->>'potassium_percent','')::numeric,potassium_percent),magnesium_percent=coalesce(nullif(p_payload->>'magnesium_percent','')::numeric,magnesium_percent),calcium_percent=coalesce(nullif(p_payload->>'calcium_percent','')::numeric,calcium_percent),note=nullif(btrim(p_payload->>'note'),''),is_active=coalesce((p_payload->>'is_active')::boolean,is_active),official_registration_id=v_official,official_registration_no=v_reg,official_source_date=v_source,updated_at=now() where id=v_id;select to_jsonb(f) into v_after from public.fertilizers f where f.id=v_id;insert into public.audit_logs(user_id,action,entity_type,entity_id,before_data,after_data) values(auth.uid(),'UPDATE','fertilizer',v_id::text,v_before,v_after);end if;return v_id;exception when unique_violation then raise exception 'この公式登録肥料はすでに肥料マスタへ登録されています';end $$;
revoke all on function public.admin_save_fertilizer(jsonb) from public,anon;grant execute on function public.admin_save_fertilizer(jsonb) to authenticated;
